(*
 * SpxAbout -- what the About box says, built from the files that already say it.
 *
 * GENERATED by scripts/make-about.py from NOTICE.md, VERSION and the engine
 * submodule's tag. Do not edit: change those and run the script again.
 *
 * NOTICE.md asks for this in as many words -- "anything here that requires
 * attribution must also appear in the application's About box" -- and the point of
 * generating it is that the two copies cannot drift. The suite checks that every
 * licence named in the file is named here, and that every entry the file OBLIGES us
 * to show is in the text that ships.
 *)
unit SpxAbout;

{$mode objfpc}{$H+}

interface

const
  { Four parts, because that is what a Store package manifest wants. One line, in
    VERSION at the root, so the manifest and the screen cannot disagree. }
  SPX_VERSION = '0.1.1.0';
  { The engine this was built against -- the submodule tag, read from git at
    generation. Someone reporting a difference from another engine in the family
    needs to know which one answered here. }
  SPX_ENGINE_VERSION = 'v0.5.1';

{ The attributions, one line at a time, in the order NOTICE.md gives them. }
function SpxAboutLineCount: Integer;
function SpxAboutLine(AIndex: Integer): string;

{ Every licence NOTICE.md names, and every entry it obliges the application to show.
  Here so the suite can hold the two files to each other. }
function SpxAboutLicenceCount: Integer;
function SpxAboutLicence(AIndex: Integer): string;
function SpxAboutObligedCount: Integer;
function SpxAboutObliged(AIndex: Integer): string;

implementation

const
  ABOUT_LINE: array[0..28] of string = (
    'Requires attribution in the shipped application',
    '',
    'Spintax Studio -- GNU General Public License v3.0 or later',
    '  Copyright (c) 2026 301.st. <https://301.st/> Additional permission under GPL v3 section 7 for the MPL-1.1 components it links (SynEdit and IPro); the grant is at the top of NOTICE.md. SPINTAX language reference: <https://spintax.net/>',
    '',
    'Material Design Icons -- Apache License 2.0',
    '  the font glyphs used by the application controls: diagnostics, variables, variants, the group editor, reroll, copy, preview modes, search/navigation and editor controls. The help and insert-example cells are drawn by the project and are not MDI glyphs. Apache License 2.0, © Pictogrammers and contributors. <https://pictogrammers.com/library/mdi/> The MDI cells listed in `scripts/make-icons.py` are rendered from the project''s webfont into `assets/icons/` and embedded as `gui/SpxIcons.pas`. The font itself is not redistributed.',
    '',
    'Twemoji -- CC-BY 4.0',
    '  the fourteen flags beside the interface languages. CC-BY 4.0, © 2020 Twitter, Inc and other contributors. <https://github.com/twitter/twemoji> The 72 px originals are vendored in `assets/flags/` and scaled into the sprite embedded as `gui/SpxFlags.pas`. A flag stands for a country and a menu item names a language; where the two disagree the choice is recorded, one line per language, in `scripts/make-flags.py`.',
    '',
    'Linked libraries',
    '',
    'Free Pascal RTL and FCL -- modified LGPL (LGPL with the static-linking exception)',
    '  The exception exists precisely so a statically linked executable may be distributed under its own terms; Studio is GPL-3.0-or-later, which the LGPL permits combining with in any case, and no further obligation follows.',
    '',
    'Lazarus LCL -- modified LGPL',
    '  Same exception, same conclusion. <https://www.lazarus-ide.org/>',
    '',
    'SynEdit -- MPL 1.1',
    '  The editor component; unmodified.',
    '',
    'TurboPower Internet Professional (IPro) -- MPL 1.1',
    '  The HTML preview; unmodified. MPL 1.1 covers the files themselves: a change to either component''s source would have to be published. We use both as they ship, so nothing here is ours to publish — if that ever stops being true, this line stops being true with it. MPL 1.1 does not combine with the GPL on its own, which is what the additional permission at the top of this file is for: SynEdit''s own headers offer "GPL Version 2 or later" as an alternative and would not need it, IPro''s offer nothing of the kind and do.',
    '',
    'The engine',
    '',
    'spintax-win -- MIT',
    '  is our own, MIT-licensed, and is a git submodule rather than a copy (`engine/`, pinned by tag). Its notice is its own file, in its own repository.'
  );

  ABOUT_LICENCE: array[0..6] of string = (
    'GNU General Public License v3.0 or later',
    'Apache License 2.0',
    'CC-BY 4.0',
    'modified LGPL (LGPL with the static-linking exception)',
    'modified LGPL',
    'MPL 1.1',
    'MIT'
  );

  ABOUT_OBLIGED: array[0..2] of string = (
    'Spintax Studio',
    'Material Design Icons',
    'Twemoji'
  );

function SpxAboutLineCount: Integer;
begin
  Result := Length(ABOUT_LINE);
end;

function SpxAboutLine(AIndex: Integer): string;
begin
  if (AIndex < 0) or (AIndex > High(ABOUT_LINE)) then Exit('');
  Result := ABOUT_LINE[AIndex];
end;

function SpxAboutLicenceCount: Integer;
begin
  Result := Length(ABOUT_LICENCE);
end;

function SpxAboutLicence(AIndex: Integer): string;
begin
  if (AIndex < 0) or (AIndex > High(ABOUT_LICENCE)) then Exit('');
  Result := ABOUT_LICENCE[AIndex];
end;

function SpxAboutObligedCount: Integer;
begin
  Result := Length(ABOUT_OBLIGED);
end;

function SpxAboutObliged(AIndex: Integer): string;
begin
  if (AIndex < 0) or (AIndex > High(ABOUT_OBLIGED)) then Exit('');
  Result := ABOUT_OBLIGED[AIndex];
end;

end.
