(*
 * SpxHelpText -- the help documents, as HTML, one page per section.
 *
 * GENERATED by scripts/make-help.py from docs/help/<lang>/diagnostics.md. Do not edit:
 * change the markdown and run the script again. The markdown is the single source --
 * TestHelpExamples runs every example in it through the real engine, so what ships here
 * cannot diverge from what was verified. The suite compares SpxHelpSourceDigest against
 * the file on disk, which is what makes "edited the markdown, forgot to regenerate" a
 * failing build rather than a stale window.
 *
 * A PAGE PER SECTION. TIpHtmlPanel's layout is quadratic -- measured 156 ms on 12.7 KB,
 * and 12.9 s on 172 KB (ADR 0004). Whole documents would be seconds.
 *
 * The index is ALang * SPX_HELP_PAGE_COUNT + APage. Both documents carry the same
 * sections in the same order, and the script refuses to write unless they do, because a
 * slug names a section in BOTH -- that is how the viewer keeps your place when the
 * interface language changes.
 *)
unit SpxHelpText;

{$mode objfpc}{$H+}

interface

const
  SPX_HELP_LANG_COUNT = 2;
  SPX_HELP_PAGE_COUNT = 12;

{ The help languages, by the engine's own code. Not the interface's fourteen: a
  language with no document here falls back, and SpxHelpNav owns that rule. }
function SpxHelpLangCode(ALang: Integer): string;
function SpxHelpLangIndex(const ACode: string): Integer;   { -1 when absent }

{ Where the document came from, and an FNV-1a of its bytes. The suite reads the file and
  compares -- an edit without a regeneration fails the build. }
function SpxHelpSourcePath(ALang: Integer): string;
function SpxHelpSourceDigest(ALang: Integer): string;

{ A page. The slug is the same string in every language; the title is that language's. }
function SpxHelpPageSlug(APage: Integer): string;
function SpxHelpPageIndex(const ASlug: string): Integer;   { -1 when absent }
function SpxHelpPageTitle(ALang, APage: Integer): string;

{ The page's HTML -- a FRAGMENT, with no <html> around it. SpxHelpNav.SpxHelpDocument
  wraps it, and the renderer must never be handed a bare fragment (ADR 0004). }
function SpxHelpPageHtml(ALang, APage: Integer): string;

{ The `###` articles of a language, in document order. IsCode says the id is a
  diagnostic code, which is what a row in the panel can be looked up by. }
function SpxHelpAnchorCount(ALang: Integer): Integer;
function SpxHelpAnchorPage(ALang, AIndex: Integer): Integer;
function SpxHelpAnchorId(ALang, AIndex: Integer): string;
function SpxHelpAnchorTitle(ALang, AIndex: Integer): string;
function SpxHelpAnchorIsCode(ALang, AIndex: Integer): Boolean;

{ THE CONDITIONS THE OUTPUTS WERE MEASURED UNDER, from the document's own spx-fixture
  block. A click rendered under anything else would disagree with the arrow printed
  beside it, which is the one thing this document may never do. }
function SpxHelpLocale(ALang: Integer): string;
function SpxHelpSeed(ALang: Integer): LongWord;
function SpxHelpIncludeCount(ALang: Integer): Integer;
function SpxHelpIncludeName(ALang, AIndex: Integer): string;
function SpxHelpIncludeText(ALang, AIndex: Integer): string;

{ THE TEMPLATE BEHIND A LINK. Every example`s template is an `ex:N` anchor in the page,
  and this is what N means -- stored verbatim, as the fixture rendered it, so a click
  runs exactly what the suite verified. The window parses nothing: it is handed the
  href and asks here. False for a number this build does not have. }
function SpxHelpExampleCount(ALang: Integer): Integer;
function SpxHelpExample(ALang, AIndex: Integer; out ATemplate: string): Boolean;
{ `ex:7` -> 7, or -1 for anything else. The one place the href form is known. }
function SpxHelpExampleOf(const AHref: string): Integer;

implementation

const
  HELP_LANG: array[0..1] of string = ('en', 'ru');
  HELP_PATH: array[0..1] of string = ('docs/help/en/diagnostics.md', 'docs/help/ru/diagnostics.md');
  HELP_DIGEST: array[0..1] of string = ('1d55b75bd2937b92', 'e6d9838e84f31c40');

  HELP_SLUG: array[0..11] of string = (
    'about', 'reading', 'brackets', 'definitions', 'variables', 'includes', 'plurals', 'permutations', 'notes', 'abbreviations', 'correct', 'faq'
  );

  { Titles, indexed ALang * SPX_HELP_PAGE_COUNT + APage. }
  HELP_TITLE: array[0..23] of string = (
    'What the Diagnostics tab is telling you',
    'How to read the examples',
    'Brackets',
    'Definitions',
    'Variables',
    'Includes',
    'Plurals',
    'Permutations',
    'Studio notes with nothing to show',
    'A silence in every language: abbreviations',
    'What the correct form looks like',
    'Frequently asked',
    'Что говорит вкладка «Диагностика»',
    'Как читать примеры',
    'Скобки',
    'Определения',
    'Переменные',
    'Вставки',
    'Множественное число',
    'Перестановки',
    'Заметки Studio, которым нечего показать',
    'Молчание, которое встречают все: сокращения',
    'Как выглядит правильное',
    'Часто спрашивают'
  );

  { First and last line of each page in HELP_LINE, same index. }
  HELP_FIRST: array[0..23] of Integer = (
    0, 10, 17, 28, 44, 68, 86, 105, 116, 129, 142, 150, 157, 168, 174, 187, 203, 227, 245, 264, 275, 288, 303, 311
  );
  HELP_LAST: array[0..23] of Integer = (
    9, 16, 27, 43, 67, 85, 104, 115, 128, 141, 149, 156, 167, 173, 186, 202, 226, 244, 263, 274, 287, 302, 310, 316
  );

  { Every page of every language, one element per line of HTML -- a change to the
    prose is then one readable hunk in a diff, which a byte array would not be. }
  HELP_LINE: array[0..316] of string = (
    '<h1 id="about">What the Diagnostics tab is telling you</h1>',
    '<p>Every line in that tab is a verdict from the <b>engine</b>, and the same verdict yo' +
      'u would get from the JavaScript, PHP or Python implementation — four independent engin' +
      'es held to one shared corpus. It is not Studio''s opinion about your template. If the ' +
      'engine calls something an error here, every other engine in the family calls it an err' +
      'or too, and your template will behave the same way on your server as it does in this w' +
      'indow.</p>',
    '<table border=1 cellpadding=4 cellspacing=0 width="100%">',
    '<tr><th>what it says</th><th>who says it</th><th>what it means</th></tr>',
    '<tr><td><b>error</b></td><td>the engine</td><td>the template will not do what it looks' +
      ' like it does</td></tr>',
    '<tr><td><b>warning</b></td><td>the engine</td><td>it renders, but probably not the way' +
      ' you meant</td></tr>',
    '<tr><td><b>Studio note</b></td><td>Studio</td><td>the engine said nothing, and it is s' +
      'till worth saying: a circular include, a target whose case differs, a control characte' +
      'r</td></tr>',
    '</table>',
    '<p>The <b>Where</b> column is a line and a column. Clicking the row puts the caret the' +
      're.</p>',
    '<blockquote>Every example below was run through <code>spintax-win v0.3.3</code>, and t' +
      'he right-hand side is exactly what it returned. Nothing here is remembered or guessed.' +
      '</blockquote>',
    '<h2 id="reading">How to read the examples</h2>',
    '<p>The arrow <code>→</code> separates the template from what the engine returned. <cod' +
      'e>⏎</code> is a line break inside an output, <code>(empty)</code> means it printed not' +
      'hing at all, and <code>…</code> marks an output too long to show in full. Text after t' +
      'he output, set off by three spaces, is a note rather than part of the answer.</p>',
    '<p>The conditions the examples were run under are here rather than hidden in the tests' +
      ' — without them some answers cannot be reproduced. The template set matters most: othe' +
      'rwise <code>#include "frag"</code> → <code>Fragment</code> would rest on something thi' +
      's document never states.</p>',
    '<pre>locale: en' +
      #10 +
      'seed: 7' +
      #10 +
      'empty: (empty)' +
      #10 +
      'include frag: Fragment' +
      #10 +
      'include loop: #include "loop"' +
      #10 +
      'include Intro: Introduction</pre>',
    '<p><code>seed</code> pins the random choice: without it an enumeration or a permutatio' +
      'n would answer differently every time and there would be nothing to check.</p>',
    '<p><b>The locale is <code>en</code> here, and it decides two things:</b> how many plur' +
      'al forms the engine expects, and which form goes with which number. English asks for t' +
      'wo. Russian, Ukrainian, Belarusian, Serbian, Croatian and Bosnian ask for three. The l' +
      'ocale comes from the selector above the right-hand pane, not from the language of the ' +
      'interface.</p>',
    '<hr>',
    '<h2 id="brackets">Brackets</h2>',
    '<h3 id="bracket.unclosed"><code>bracket.unclosed</code> — a bracket is opened and neve' +
      'r closed</h3>',
    '<pre><a href="ex:0">a price {cheap|dear</a>          →  A price {cheap|dear</pre>',
    '<p>The engine does not guess where you meant to close it. The text stays as it is, bra' +
      'ce and all, and the choice never happens.</p>',
    '<h3 id="bracket.mismatched"><code>bracket.mismatched</code> — closed by a bracket of a' +
      'nother kind</h3>',
    '<pre><a href="ex:1">a price {cheap|dear]</a>         →  A price {cheap|dear]</pre>',
    '<p><code>{</code> waits for <code>}</code> and <code>[</code> waits for <code>]</code>' +
      '. A permutation closed by a brace is not a permutation.</p>',
    '<h3 id="bracket.unexpected-closing"><code>bracket.unexpected-closing</code> — a closin' +
      'g bracket with nothing open</h3>',
    '<pre><a href="ex:2">a price cheap} and all</a>       →  A price cheap} and all</pre>',
    '<p>Most often a leftover from an edit: the opening brace was deleted and the closing o' +
      'ne stayed.</p>',
    '<hr>',
    '<h2 id="definitions">Definitions</h2>',
    '<h3 id="set.malformed"><code>set.malformed</code> — this <code>#set</code> line does n' +
      'ot follow the rule</h3>',
    '<pre><a href="ex:3">#set city = Boston</a>' +
      #10 +
      '<a href="ex:3">in %city%</a>                    →  #set city = Boston ⏎ In %city%</pre' +
      '>',
    '<p><b>The name goes in per cent signs:</b> <code>#set %city% = Boston</code>. This is ' +
      'the commonest first mistake and it puts two lines in the panel at once — the malformed' +
      ' line itself, and "this variable is defined nowhere", because no definition happened a' +
      'nd <code>%city%</code> belongs to nobody.</p>',
    '<p>Look at the output: the failed directive stayed in the text <b>as written</b>. The ' +
      'engine did not read it as a directive, so it is an ordinary line and it goes into the ' +
      'result.</p>',
    '<h3 id="def.malformed"><code>def.malformed</code> — this <code>#def</code> line does n' +
      'ot follow the rule</h3>',
    '<pre><a href="ex:4">#def pages = {1|3}</a>' +
      #10 +
      '<a href="ex:4">%pages%</a>                      →  #def pages = 1 ⏎ %pages%</pre>',
    '<p>The same rule and the same price. <code>#def</code> differs from <code>#set</code> ' +
      'not in spelling but in <b>when</b> the value is expanded: <code>#set</code> expands it' +
      ' again at every reference, <code>#def</code> once per render. A mistake in the writing' +
      ' costs you both.</p>',
    '<p>And look closely at the output: the <code>{1|3}</code> inside the failed directive ' +
      '<b>picked a variant</b>. The line became ordinary text — and ordinary text is rendered' +
      ' like ordinary text, braces and all. A malformed line is not switched off; it merely s' +
      'tops being a directive.</p>',
    '<h3 id="definition.duplicate-name"><code>definition.duplicate-name</code> — this name ' +
      'is already defined above</h3>',
    '<pre><a href="ex:5">#set %x% = first</a>' +
      #10 +
      '<a href="ex:5">#set %x% = second</a>' +
      #10 +
      '<a href="ex:5">%x%</a>                          →  Second</pre>',
    '<p>It works — the <b>last</b> definition wins — but the engine calls it an error: a do' +
      'cument where one name is set twice reads ambiguously, and in a month you will not reme' +
      'mber which of the two lines is the live one. The error points at the <b>second</b> def' +
      'inition; the first is further up.</p>',
    '<h3 id="def.include-in-value"><code>def.include-in-value</code> — <code>#include</code' +
      '> inside a definition value</h3>',
    '<pre><a href="ex:6">#def %x% = #include "frag"</a>' +
      #10 +
      '<a href="ex:6">%x%</a>                          →  Fragment</pre>',
    '<p>An include inside a value expands at a different moment than you would expect, and ' +
      'the family forbids it. Put the <code>#include</code> on a line of its own.</p>',
    '<hr>',
    '<h2 id="variables">Variables</h2>',
    '<h3 id="variable.undefined"><code>variable.undefined</code> — this variable is defined' +
      ' nowhere</h3>',
    '<pre><a href="ex:7">hello, %name%</a>                →  Hello, %name%</pre>',
    '<p>A warning rather than an error: the engine prints the name as it stands. That is by' +
      ' design — the value may arrive from outside, from the host. In Studio you supply such ' +
      'values on the Variables tab, under <b>Session values</b>.</p>',
    '<p><b>A definition''s value can be edited in the panel.</b> Stand on the Value column ' +
      'in the upper section and press <b>F2</b> (or just start typing); <b>Enter</b> applies,' +
      ' <b>Escape</b> abandons. The edit goes <b>into the document</b>, in one undo step: <co' +
      'de>Ctrl+Z</code> puts it back.</p>',
    '<p>Exactly the value changes. The indentation, the extra spaces, the case of the name ' +
      'and a trailing comment all stay as they were — the file is in git, and reformatting a ' +
      'line would show up there as your change.</p>',
    '<p><b>A refusal means the engine would read the line differently.</b> The edit is not ' +
      'applied silently: the engine reads the result back, and if it does not say what was as' +
      'ked, the document is left alone and the status bar says so. Three real causes: <code>/' +
      '#</code> in the value opens a comment that eats the rest of the file, a line break end' +
      's the directive early, and a comment <b>inside</b> the directive makes the line un-edi' +
      'table in pieces — edit that one in the text.</p>',
    '<p><b>Two gestures on a variable''s name.</b> The name in the panel is a link, not a l' +
      'abel:</p>',
    '<ul>',
    '<li><b>click the name</b> and the caret moves to the first place the document uses tha' +
      't variable, and the line lights up for a moment. The same word inside a comment or as ' +
      'an <code>#include</code> target does <b>not</b> count — the panel takes you where the ' +
      'variable actually works.</li>',
    '<li><b>Ctrl+click</b> writes a definition into the document and opens the group editor' +
      ' on it. The value you have already typed moves in as its first option:</li>',
    '</ul>',
    '<pre><a href="ex:8">#set %brand% = {Vulkan}</a>' +
      #10 +
      '<a href="ex:8">casino %brand%</a>               →  Casino Vulkan</pre>',
    '<p>The difference between the two is what survives closing the window. A session value' +
      ' does not: it is not in the file, not in git, and no other engine in the family can se' +
      'e it. A definition does, and only a definition silences this warning for good. One <co' +
      'de>Ctrl+Z</code> puts the document back.</p>',
    '<p><b>A session value is a template by default, not text.</b> That is what the engine ' +
      'does with any host value, and the preview has to match the production server — so <cod' +
      'e>{cheap|dear}</code> typed into the value field gives a choice, not those eleven char' +
      'acters. If you meant the text itself, tick <b>as text</b> in the third column: then br' +
      'aces and per cent signs stay characters.</p>',
    '<h3 id="variable.self-reference"><code>variable.self-reference</code> — the definition' +
      ' refers to itself</h3>',
    '<pre><a href="ex:9">#set %x% = a %x% b</a>' +
      #10 +
      '<a href="ex:9">%x%</a>                          →  A a a … %x% … b b b</pre>',
    '<p>Fifty levels, then a stop. The engine expands to the depth limit and halts, leaving' +
      ' <code>%x%</code> in the middle. Not a loop, and not what you wanted either.</p>',
    '<p>The <code>…</code> above is this document''s abbreviation, not the engine''s. The r' +
      'eal output is 207 characters and carries <b>fifty-one</b> letters on each side rather ' +
      'than fifty: the fiftieth level stops and leaves the value as it stands, and the value ' +
      'holds one more of each.</p>',
    '<h3 id="variable.circular-reference"><code>variable.circular-reference</code> — the de' +
      'finitions refer in a circle</h3>',
    '<pre><a href="ex:10">#set %x% = %y%</a>' +
      #10 +
      '<a href="ex:10">#set %y% = %x%</a>' +
      #10 +
      '<a href="ex:10">%x%</a>                          →  %y%</pre>',
    '<p>Each side expands exactly <b>once</b> and then stops: <code>%x%</code> became <code' +
      '>%y%</code>, not <code>%x%</code>. The engine unwinds rather than looping, and what su' +
      'rvives is the other name in the circle — put <code>%x% %y%</code> in a document and it' +
      ' renders <code>%y% %x%</code>, the pair swapped.</p>',
    '<p>The panel draws a row for <b>each</b> definition in the circle, not one for the cir' +
      'cle.</p>',
    '<hr>',
    '<h2 id="includes">Includes</h2>',
    '<h3 id="includes-0"><code>#include</code> only works from the start of a line</h3>',
    '<pre><a href="ex:11">before #include "frag" after</a> →  Before #include "frag" after<' +
      '/pre>',
    '<pre><a href="ex:12">#include "frag"</a>              →  Fragment</pre>',
    '<p>Not a diagnostic, and that is the point: an <code>#include</code> in the middle of ' +
      'a line is <b>not</b> an include. The engine reads it as ordinary text and says nothing' +
      ', because there is nothing to complain about — you wrote text and got text.</p>',
    '<h3 id="include.unknown-target"><code>include.unknown-target</code> — no such target i' +
      'n the set</h3>',
    '<pre><a href="ex:13">#include "nosuch"</a>            →  (empty)</pre>',
    '<p>Targets are the <code>.spintax</code> files in the folder of the open document. An ' +
      'unknown target expands to nothing — the paragraph disappears rather than breaking, whi' +
      'ch is exactly why it is easy to miss.</p>',
    '<p><b>That is why the Variables tab has a third section, Includes.</b> It lists every ' +
      '<code>#include</code> the document contains and, for each, whether the set has its tar' +
      'get — one row per occurrence, so a target named twice is two rows. The section appears' +
      ' only when the document has includes. Clicking a row moves the caret to the <code>#inc' +
      'lude</code> that names that target.</p>',
    '<p>The mark has <b>three</b> values, and the third matters: <code>no set</code> is not' +
      ' "the fragment is missing", it is "there is nowhere to look yet". The set is the folde' +
      'r beside the document, and an unsaved document has no folder — so until the first save' +
      ' every target is marked that way. <code>MISSING</code> appears only when there is a fo' +
      'lder and the file really is not in it.</p>',
    '<h3 id="note.case-mismatch"><code>note.case-mismatch</code> — the target exists, in an' +
      'other case</h3>',
    '<pre><a href="ex:14">#include "intro"</a>             →  (empty)</pre>',
    '<p>The set holds <code>Intro.spintax</code> — and the engine still says there is no su' +
      'ch target, while Studio adds its note about the case. Case matters: <code>intro</code>' +
      ' and <code>Intro</code> are different targets. Windows would open the file in either c' +
      'ase, which is why Studio looks in the set rather than on the file system: otherwise th' +
      'e preview would disagree with the production server about the same document.</p>',
    '<h3 id="note.cycle"><code>note.cycle</code> — an include in a circle</h3>',
    '<p>If <code>loop.spintax</code> contains <code>#include "loop"</code>, then:</p>',
    '<pre><a href="ex:15">#include "loop"</a>              →  (empty)</pre>',
    '<p>The engine substitutes nothing rather than infinity. The note is there so you know ' +
      'why the paragraph vanished.</p>',
    '<hr>',
    '<h2 id="plurals">Plurals</h2>',
    '<h3 id="plural.arity"><code>plural.arity</code> — not as many forms as the locale asks' +
      ' for</h3>',
    '<pre><a href="ex:16">#set %n% = 5</a>' +
      #10 +
      '<a href="ex:16">%n% {plural %n%: item|items|itemses}</a>   →  5 ｛plural 5: item|items|' +
      'itemses｝</pre>',
    '<p><b>Not emptiness — the engine prints the whole construct</b>, with the braces repla' +
      'ced by wide ones <code>｛｝</code>. That is how it says "I saw this and could not apply ' +
      'it". Nobody would call that unnoticeable, and that is good: a paragraph that vanished ' +
      'silently would take longer to find.</p>',
    '<p>English asks for two forms, Russian for three. Under this document''s locale <code>' +
      '{plural %n%: item|items}</code> is the correct one.</p>',
    '<p><b>Emptiness happens for another reason, and the two are easy to confuse.</b> Compa' +
      're these two, which differ only in how many forms they carry:</p>',
    '<pre><a href="ex:17">{plural %n%: item|items}</a>             →  (empty)   two forms: ' +
      'right for English' +
      #10 +
      '<a href="ex:18">{plural %n%: item|items|itemses}</a>     →  (empty)   three forms: wro' +
      'ng for English</pre>',
    '<p>Both print nothing, and the panel treats them differently: the first draws only <co' +
      'de>variable.undefined</code>, the second draws <code>plural.arity</code> as well. So <' +
      'b>emptiness is not the mark of an arity error</b> — here it comes from <code>%n%</code' +
      '> being undefined, and the engine checks the count before it counts the forms, stoppin' +
      'g before the question of arity arises.</p>',
    '<p>That is why the example at the top of this article defines <code>%n%</code> first. ' +
      'Without it the output would be empty whatever the number of forms, and would demonstra' +
      'te nothing about arity at all.</p>',
    '<h3 id="plural.count-macro"><code>plural.count-macro</code> — the count comes from <co' +
      'de>#set</code>, and that rerolls on every reference</h3>',
    '<pre><a href="ex:19">#set %n% = {1|2}</a>' +
      #10 +
      '<a href="ex:19">%n% {plural %n%: item|items}</a>   →  1</pre>',
    '<p>Look at what survived: <b>the number printed and the noun did not.</b> The count ha' +
      's to be a number by the time the plural is chosen, and a <code>#set</code> whose value' +
      ' is itself a choice never becomes one — the engine substitutes the value <b>without re' +
      'ndering it</b>, so what lands in the count slot is the literal text <code>{1|2}</code>' +
      '. The count and the form cannot disagree; the engine drops the word instead.</p>',
    '<p><code>#def</code> behaves differently, expanding its value once per render, so the ' +
      'count slot gets a number:</p>',
    '<pre><a href="ex:20">#def %n% = {1|2}</a>' +
      #10 +
      '<a href="ex:20">%n% {plural %n%: item|items}</a>   →  1 item</pre>',
    '<p>There is no panel row at all for that one. Hence the rule: make the count a plain n' +
      'umber or a <code>#def</code>, never a <code>#set</code>.</p>',
    '<h3 id="plural.nested-brackets"><code>plural.nested-brackets</code> — brackets inside ' +
      'the plural forms</h3>',
    '<pre><a href="ex:21">{plural %n%: {item|thing}|items}</a>   →  ｛plural %n%: ｛item|thin' +
      'g｝|items｝</pre>',
    '<p>Forms are plain text. A choice inside them is not expanded, and the whole construct' +
      ' is printed in wide braces instead.</p>',
    '<hr>',
    '<h2 id="permutations">Permutations</h2>',
    '<h3 id="permutation.unknown-key"><code>permutation.unknown-key</code> — unknown key in' +
      ' the permutation config</h3>',
    '<pre><a href="ex:22">[&lt;foo=1&gt;a|b|c]</a>               →  Bfoo=1cfoo=1a</pre>',
    '<p>The known keys are <code>minsize</code>, <code>maxsize</code>, <code>sep</code> and' +
      ' <code>lastsep</code>. An unknown one is not a setting — it becomes the separator betw' +
      'een the elements, which is what the output shows.</p>',
    '<h3 id="permutation.minsize-not-integer"><code>permutation.minsize-not-integer</code> ' +
      '— minsize is not a whole number</h3>',
    '<pre><a href="ex:23">[&lt;minsize=two&gt;a|b|c]</a>         →  B c a</pre>',
    '<p>A non-numeric value is dropped along with its limit, and the default is used — whic' +
      'h is all the elements.</p>',
    '<h3 id="permutation.maxsize-not-integer"><code>permutation.maxsize-not-integer</code> ' +
      '— maxsize is not a whole number</h3>',
    '<pre><a href="ex:24">[&lt;maxsize=many&gt;a|b|c]</a>        →  B c a</pre>',
    '<p>Exactly the same from the other end: the upper limit disappears, and the output aga' +
      'in holds every element.</p>',
    '<hr>',
    '<h2 id="notes">Studio notes with nothing to show</h2>',
    '<p>The three notes below cannot be demonstrated by an example in this document, and th' +
      'e reason is different in each case and stated. They still have articles: the help owes' +
      ' an answer to <b>every</b> code the panel can show, or a row in the panel leads nowher' +
      'e.</p>',
    '<h3 id="note.raw-sentinel"><code>note.raw-sentinel</code> — a control character in the' +
      ' text</h3>',
    '<p>The characters U+E000–U+E005 are what the engine uses for its own markup, and it <b' +
      '>removes</b> them before parsing. If they reached your template — usually pasted in fr' +
      'om another editor — Studio says so: neither the preview nor the production server will' +
      ' show them.</p>',
    '<p>There is no example here on purpose: those characters are invisible, and a line car' +
      'rying them would look empty. There would be nothing to see.</p>',
    '<h3 id="note.unknown-target"><code>note.unknown-target</code> — the set is empty, so t' +
      'here is nothing to judge by</h3>',
    '<p>It appears when the set beside the document is <b>empty</b>: not one template besid' +
      'es this one. There is nothing to check the target against, so Studio does not say "no ' +
      'such target" — it says it cannot answer. Put a single template in that folder and the ' +
      'note gives way to the ordinary <code>include.unknown-target</code>, which answers on t' +
      'he merits.</p>',
    '<p>A document that has never been saved has no set <b>at all</b>, and that is a third ' +
      'case, not this one: includes then stay in the output verbatim and the panel says nothi' +
      'ng about them. Save the document and they start working.</p>',
    '<p>There is no example here by construction: this document''s set is declared above an' +
      'd is not empty.</p>',
    '<h3 id="note.too-deep"><code>note.too-deep</code> — includes nested too deeply</h3>',
    '<p>The engine stops at the twentieth level of nested <code>#include</code> and substit' +
      'utes nothing below it. The limit belongs to the family: the JavaScript, PHP and Python' +
      ' engines do the same, so a document that hits it behaves identically everywhere.</p>',
    '<p>There is no example because of its size: showing one would take twenty-one files.</' +
      'p>',
    '<hr>',
    '<h2 id="abbreviations">A silence in every language: abbreviations</h2>',
    '<h3 id="abbreviations-0">An abbreviation keeps the next word lowercase</h3>',
    '<pre><a href="ex:25">Ltd. our prices are low</a>      →  Ltd. our prices are low' +
      #10 +
      '<a href="ex:26">Xyz. our prices are low</a>      →  Xyz. Our prices are low</pre>',
    '<p>Two lines that differ by one word, and the second word of each tells you the rule: ' +
      'after <code>Ltd.</code> the sentence stays lowercase, after <code>Xyz.</code> it is ca' +
      'pitalised. The engine capitalises after a full stop — except after an abbreviation it ' +
      'knows, and anything shaped like <code>e.g.</code> or <code>U.S.</code>. It is silent: ' +
      'no diagnostic, no warning, and the only way to notice is to read the output.</p>',
    '<p><b>The list is not English.</b> It holds 46 entries, and 29 of them are Russian:</p' +
      '>',
    '<table border=1 cellpadding=4 cellspacing=0 width="100%">',
    '<tr><th></th><th></th></tr>',
    '<tr><td>English</td><td><code>etc vs mr mrs ms dr prof sr jr inc ltd co corp no st ave' +
      ' blvd</code></td></tr>',
    '<tr><td>Russian</td><td><code>соц эл см ср ст ул пр пер г р руб коп тыс млн млрд трлн ' +
      'доп напр прим изд обл респ стр табл рис мин макс тел факс</code></td></tr>',
    '</table>',
    '<p>Both halves are live in <b>both</b> locales — the rule never asks what language you' +
      ' set. So <code>руб.</code> shields the next word in an English document, <code>Ltd.</c' +
      'ode> shields it in a Russian one, and an English author who writes <code>no.</code> or' +
      ' <code>st.</code> mid-sentence is using a Russian-length list without knowing it.</p>',
    '<p>It bites in one place: a sentence that legitimately begins after <code>No.</code>, ' +
      '<code>St.</code> or <code>Co.</code> comes out lowercase. Rewrite the sentence rather ' +
      'than fighting the rule — the same shielding is what keeps <code>e.g. this</code> from ' +
      'being capitalised mid-sentence, which is far commoner.</p>',
    '<hr>',
    '<h2 id="correct">What the correct form looks like</h2>',
    '<pre><a href="ex:27">a price {cheap|dear}</a>         →  A price cheap</pre>',
    '<pre><a href="ex:28">[&lt;minsize=2;sep=", "&gt;a|b|c]</a>  →  C, b</pre>',
    '<pre><a href="ex:29">#set %vip% = 1</a>' +
      #10 +
      '<a href="ex:29">{?vip?for you|for everyone}</a>  →  For you</pre>',
    '<pre><a href="ex:30">#set %n% = 5</a>' +
      #10 +
      '<a href="ex:30">%n% {plural %n%: item|items}</a> →  5 items</pre>',
    '<pre><a href="ex:31">before /# a note #/ after</a>    →  Before after</pre>',
    '<p>Five constructions, five clean lines in the panel — which is to say none at all.</p' +
      '>',
    '<hr>',
    '<h2 id="faq">Frequently asked</h2>',
    '<p><b>Why did the paragraph simply disappear?</b> Two common causes, both above: an un' +
      'known <code>#include</code> target and an include in a circle. Both print nothing. The' +
      ' third one people suspect first — the wrong number of plural forms — does <b>not</b> p' +
      'rint nothing: the engine prints the whole construct in wide braces <code>｛｝</code>. Em' +
      'ptiness there comes from a non-numeric count, not from the number of forms.</p>',
    '<p><b>Why does my variable with a non-ASCII name not work?</b> Names are ASCII letters' +
      ', digits and the underscore. <code>%café%</code> is not a variable reference at all — ' +
      'the engine reads it as text and says nothing, because on its reading there is nothing ' +
      'to report:</p>',
    '<pre><a href="ex:32">hello %café% and %name%</a>      →  Hello %café% and %name%</pre>',
    '<p>Both came through unchanged, and that is the trap: only the second drew a row in th' +
      'e panel. The first is silent, so nothing tells you it will never be substituted. Renam' +
      'e it.</p>',
    '<p><b>I switched the locale and the document turned red.</b> That is the locale doing ' +
      'its job. The demo document is English and its plural blocks carry two forms; switch th' +
      'e locale to Russian and those two forms become an arity error, because Russian asks fo' +
      'r three. The locale belongs to the <b>document</b>, which is why Studio does not chang' +
      'e it when you change the language of the interface.</p>',
    '<p><b>Is the preview the same as what my server will produce?</b> Yes, with one condit' +
      'ion: the same engine version and the same locale. That is the whole reason the preview' +
      ' runs the real <code>spintax-win</code> rather than an approximation of it.</p>',
    '<h1 id="about">Что говорит вкладка «Диагностика»</h1>',
    '<p>Внизу окна Studio показывает вердикт о вашем шаблоне. Вердикт выносит <b>движок</b>' +
      ' — тот самый, что рисует правую панель и что стоит на боевых серверах в версиях для JS' +
      ', PHP и Python. Studio его не смягчает и не ужесточает: если здесь написано «ошибка», ' +
      'значит все движки семейства считают это ошибкой.</p>',
    '<p>Три вида строк:</p>',
    '<table border=1 cellpadding=4 cellspacing=0 width="100%">',
    '<tr><th>Уровень</th><th>Кто сказал</th><th>Что это значит</th></tr>',
    '<tr><td><b>ошибка</b></td><td>движок</td><td>конструкция разобрана не так, как вы заду' +
      'мали; вывод почти всегда не тот</td></tr>',
    '<tr><td><b>предупреждение</b></td><td>движок</td><td>разобрано, но подозрительно — чащ' +
      'е всего опечатка в имени</td></tr>',
    '<tr><td><b>заметка Studio</b></td><td>Studio</td><td>движок промолчал, но сказать стои' +
      'т: вставка по кругу, регистр цели, служебный символ</td></tr>',
    '</table>',
    '<p>Столбец «Место» — строка и колонка. Щелчок по строке ставит туда курсор.</p>',
    '<blockquote>Все примеры ниже прогнаны через движок <code>spintax-win v0.3.3</code>, и ' +
      'в колонке «выводит» написано ровно то, что он вернул. Ничего не выдумано и не пересказ' +
      'ано по памяти.</blockquote>',
    '<h2 id="reading">Как читать примеры</h2>',
    '<p>Стрелка <code>→</code> отделяет шаблон от того, что вернул движок. <code>⏎</code> —' +
      ' перенос строки внутри вывода, <code>(пусто)</code> — движок не напечатал ничего, <cod' +
      'e>…</code> — вывод слишком длинный, чтобы показать его целиком. Текст после вывода, от' +
      'делённый тремя пробелами, — пояснение, а не часть ответа.</p>',
    '<p>Условия, в которых примеры прогнаны, — здесь же, а не спрятаны в тестах: без них ча' +
      'сть ответов не воспроизвести. Набор шаблонов важен особенно — иначе пример <code>#incl' +
      'ude "frag"</code> → <code>Фрагмент</code> опирался бы на то, чего в документе не напис' +
      'ано.</p>',
    '<pre>locale: ru' +
      #10 +
      'seed: 7' +
      #10 +
      'empty: (пусто)' +
      #10 +
      'include frag: фрагмент' +
      #10 +
      'include loop: #include "loop"' +
      #10 +
      'include Intro: вступление</pre>',
    '<p><code>seed</code> фиксирует случайный выбор: без него перечисления и перестановки д' +
      'авали бы каждый раз другой ответ, и пример нечего было бы проверять.</p>',
    '<hr>',
    '<h2 id="brackets">Скобки</h2>',
    '<p><b>Поставьте каретку на скобку — и конструкция покажет себя целиком:</b> её начало,' +
      ' её конец и <b>все её разделители</b>. Вложенные группы при этом не подсвечиваются: у ' +
      'них свои разделители, и они загорятся, когда каретка встанет на их скобку. Это самый б' +
      'ыстрый способ увидеть, где кончается то, что вы правите, — особенно в длинной строке, ' +
      'где <code>}</code> уехала на два экрана вправо.</p>',
    '<p>Разделителем считается не только <code>|</code>. В перестановке <code>[a&lt;br&gt;|' +
      'b]</code> движок читает <code>&lt;br&gt;</code> как разделитель, поставленный <b>перед' +
      ' следующим</b> элементом, — и подсветка показывает его вместе с остальными, потому что' +
      ' он и есть часть строения конструкции.</p>',
    '<h3 id="bracket.unclosed"><code>bracket.unclosed</code> — скобка открыта и не закрыта<' +
      '/h3>',
    '<pre><a href="ex:0">цена {дешёвая|дорогая</a>        →  Цена {дешёвая|дорогая</pre>',
    '<p>Незакрытая группа перестаёт быть группой: движок печатает её как обычный текст, вме' +
      'сте со скобкой. Ищите пару к скобке в указанном месте.</p>',
    '<h3 id="bracket.mismatched"><code>bracket.mismatched</code> — скобка закрыта скобкой д' +
      'ругого вида</h3>',
    '<pre><a href="ex:1">цена {дешёвая|дорогая]</a>       →  Цена {дешёвая|дорогая]</pre>',
    '<p><code>{</code> закрывается только <code>}</code>, <code>[</code> только <code>]</co' +
      'de>. Смешение — почти всегда опечатка, и результат тот же, что у незакрытой: текст как' +
      ' есть.</p>',
    '<h3 id="bracket.unexpected-closing"><code>bracket.unexpected-closing</code> — закрываю' +
      'щая скобка без открывающей</h3>',
    '<pre><a href="ex:2">цена дешёвая} и всё</a>          →  Цена дешёвая} и всё</pre>',
    '<p>Обычно остаётся после того, как открывающую скобку удалили, а закрывающую забыли.</' +
      'p>',
    '<hr>',
    '<h2 id="definitions">Определения</h2>',
    '<h3 id="set.malformed"><code>set.malformed</code> — строка <code>#set</code> написана ' +
      'не по правилу</h3>',
    '<pre><a href="ex:3">#set city = Москва</a>' +
      #10 +
      '<a href="ex:3">в %city%</a>                     →  #set city = Москва ⏎ В %city%</pre>',
    '<p><b>Имя пишется в процентах:</b> <code>#set %city% = Москва</code>. Это самая частая' +
      ' ошибка новичка, и она даёт сразу две строки в панели: саму «строку не по правилу» и «' +
      'переменную нигде не определили» — потому что определения не случилось, и <code>%city%<' +
      '/code> осталась ничьей.</p>',
    '<p>Обратите внимание на вывод: несостоявшаяся директива осталась в тексте <b>как есть<' +
      '/b>. Движок не понял её как директиву — значит это обычная строка, и она попадает в ре' +
      'зультат.</p>',
    '<h3 id="def.malformed"><code>def.malformed</code> — строка <code>#def</code> написана ' +
      'не по правилу</h3>',
    '<pre><a href="ex:4">#def pages = {1|3}</a>' +
      #10 +
      '<a href="ex:4">%pages%</a>                      →  #def pages = 1 ⏎ %pages%</pre>',
    '<p>То же правило и та же цена. <code>#def</code> отличается от <code>#set</code> не на' +
      'писанием, а тем, <b>когда</b> раскрывается значение: <code>#set</code> разворачивает е' +
      'го заново при каждой ссылке, <code>#def</code> — один раз за рендер. Ошибка в записи о' +
      'динаково лишает вас и того, и другого.</p>',
    '<p>И присмотритесь к выводу: <code>{1|3}</code> в несостоявшейся директиве <b>выбрало ' +
      'вариант</b>. Строка стала обычным текстом — а обычный текст движок рендерит целиком, с' +
      'о всеми скобками, которые в нём есть. Строка «не по правилу» не выключается, она прост' +
      'о перестаёт быть директивой.</p>',
    '<h3 id="definition.duplicate-name"><code>definition.duplicate-name</code> — это имя уж' +
      'е определено выше</h3>',
    '<pre><a href="ex:5">#set %x% = первый</a>' +
      #10 +
      '<a href="ex:5">#set %x% = второй</a>' +
      #10 +
      '<a href="ex:5">%x%</a>                          →  Второй</pre>',
    '<p>Работает — побеждает <b>последнее</b> определение, — но движок считает это ошибкой:' +
      ' документ, где одно имя задано дважды, читается неоднозначно, и через месяц вы не вспо' +
      'мните, какая из двух строк живая. Ошибка указывает на <b>второе</b> определение; перво' +
      'е ищите выше по тексту.</p>',
    '<h3 id="def.include-in-value"><code>def.include-in-value</code> — <code>#include</code' +
      '> внутри значения определения</h3>',
    '<pre><a href="ex:6">#def %x% = #include "frag"</a>' +
      #10 +
      '<a href="ex:6">%x%</a>                          →  Фрагмент</pre>',
    '<p>Вставка внутри значения разворачивается не тогда, когда вы думаете, и семейство это' +
      ' запрещает. Вынесите <code>#include</code> отдельной строкой.</p>',
    '<hr>',
    '<h2 id="variables">Переменные</h2>',
    '<h3 id="variable.undefined"><code>variable.undefined</code> — переменная нигде не опре' +
      'делена</h3>',
    '<pre><a href="ex:7">привет, %name%</a>               →  Привет, %name%</pre>',
    '<p>Предупреждение, а не ошибка: движок печатает имя как есть. Так и задумано — значени' +
      'е может прийти снаружи, от хоста. В Studio такие значения задаются на вкладке «Перемен' +
      'ные», в разделе «Значения на сессию».</p>',
    '<p><b>Два жеста на имени переменной.</b> Имя в панели — ссылка, а не подпись:</p>',
    '<ul>',
    '<li><b>клик по имени</b> переносит каретку к первому месту, где документ эту переменну' +
      'ю использует, и на мгновение подсвечивает эту строку — чтобы её было видно, а не искат' +
      'ь каретку глазами. Полезнее, чем кажется: в длинной строке <code>%FoundedYear%</code> ' +
      'глазами не находится, а в комментарии или в цели <code>#include</code> то же слово пер' +
      'еходом <b>не считается</b> — панель ведёт туда, где переменная действительно работает.' +
      '</li>',
    '<li><b>Ctrl+клик</b> пишет определение в документ и открывает на нём групповой редакто' +
      'р. Значение, которое вы уже набрали в поле, переезжает в него первым вариантом:</li>',
    '</ul>',
    '<pre><a href="ex:8">#set %brand% = {Vulkan}</a>' +
      #10 +
      '<a href="ex:8">казино %brand%</a>               →  Казино Vulkan</pre>',
    '<p>Разница между двумя способами — в том, что переживёт закрытие окна. Значение сессии' +
      ' не переживает: его нет в файле, нет в git, и другие движки семейства его не видят. Оп' +
      'ределение переживает, и только оно убирает это предупреждение навсегда. Одно нажатие C' +
      'trl+Z возвращает документ, если передумали.</p>',
    '<p><b>Значение определения правится в самой панели.</b> Верхний раздел — это уже не то' +
      'лько справка: встаньте на столбец «Значение» и нажмите <b>F2</b> (или начните печатать' +
      '), <b>Enter</b> применяет, <b>Escape</b> отменяет. Правка идёт <b>в документ</b>, одни' +
      'м шагом отмены: <code>Ctrl+Z</code> возвращает как было. Имя и вид (<code>#set</code>/' +
      '<code>#def</code>) правке не подлежат — и это решение, а не незаконченность: переимено' +
      'вание из ячейки рвёт все ссылки на переменную в документе, а удаление строки уносит вм' +
      'есте с ней комментарий и отступ. Для того и другого есть текст.</p>',
    '<p>Меняется <b>ровно значение</b>. Отступ, лишние пробелы, регистр имени и комментарий' +
      ' в конце строки остаются как были: <code>   #set  %Brand%   =   Акме   /# хвост #/</co' +
      'de> после правки отличается только словом. Это не придирка к аккуратности — файл лежит' +
      ' в git, и переформатирование строки выглядело бы там как ваше изменение.</p>',
    '<p><b>Отказ означает, что движок прочитал бы строку иначе.</b> Правка не применяется м' +
      'олча: движок перечитывает результат, и если получилось не то, о чём просили, документ ' +
      'остаётся как был, а в строке состояния появляется сообщение. Три реальные причины: <co' +
      'de>/#</code> в значении открывает комментарий и съедает остаток файла, перевод строки ' +
      'заканчивает директиву раньше времени, а комментарий <b>внутри</b> директивы делает стр' +
      'оку неправимой по частям — такую строку правьте прямо в тексте.</p>',
    '<p><b>Значение сессии по умолчанию — шаблон, а не текст.</b> Так делает движок с любым' +
      ' значением хоста, и предпросмотр обязан совпадать с боевым сервером. Поэтому <code>{дё' +
      'шево|дорого}</code>, набранное в поле значения, даст выбор, а не эти восемь символов. ' +
      'Если вы имели в виду именно текст — поставьте галочку <b>«как текст»</b> в третьей кол' +
      'онке: тогда скобки и проценты останутся символами.</p>',
    '<h3 id="variable.self-reference"><code>variable.self-reference</code> — определение сс' +
      'ылается само на себя</h3>',
    '<pre><a href="ex:9">#set %x% = а %x% б</a>' +
      #10 +
      '<a href="ex:9">%x%</a>                          →  А а а … %x% … б б б</pre>',
    '<p>Пятьдесят уровней, потом остановка.</p>',
    '<p>Движок разворачивает до предела глубины и останавливается, оставляя <code>%x%</code' +
      '> в середине. Это не зацикливание, но и не то, что вам нужно.</p>',
    '<p><code>…</code> — сокращение этого документа, а не движка. Настоящий вывод занимает ' +
      '207 символов, и букв в нём по <b>пятьдесят одной</b> с каждой стороны, а не по пятьдес' +
      'ят: пятидесятый уровень останавливается и оставляет значение как есть, а в самом значе' +
      'нии лежит ещё по одной.</p>',
    '<h3 id="variable.circular-reference"><code>variable.circular-reference</code> — опреде' +
      'ления ссылаются по кругу</h3>',
    '<pre><a href="ex:10">#set %x% = %y%</a>' +
      #10 +
      '<a href="ex:10">#set %y% = %x%</a>' +
      #10 +
      '<a href="ex:10">%x%</a>                          →  %y%</pre>',
    '<p>Ошибка выдаётся на <b>каждое</b> определение в круге.</p>',
    '<hr>',
    '<h2 id="includes">Вставки</h2>',
    '<h3 id="includes-0"><code>#include</code> работает только с начала строки</h3>',
    '<p>Это не диагностика, а поведение, о которое спотыкаются чаще всего:</p>',
    '<pre><a href="ex:11">до #include "frag" после</a>     →  До #include "frag" после   (о' +
      'сталось текстом, молча)' +
      #10 +
      '<a href="ex:12">#include "frag"</a>              →  Фрагмент</pre>',
    '<p>Посреди строки <code>#include</code> — обычный текст, и <b>никакой диагностики не б' +
      'удет</b>: движок просто не увидел там директиву.</p>',
    '<h3 id="include.unknown-target"><code>include.unknown-target</code> — такой цели нет в' +
      ' наборе</h3>',
    '<pre><a href="ex:13">#include "нетакого"</a>          →  (пусто)</pre>',
    '<p>Целями считаются файлы <code>.spintax</code> в папке открытого документа. Вставка н' +
      'еизвестной цели разворачивается в пустоту — абзац исчезает, а не ломается, поэтому про' +
      'пажу легко не заметить.</p>',
    '<p><b>Поэтому на вкладке «Переменные» есть третий раздел — «Включения».</b> Он показыв' +
      'ает каждый <code>#include</code> документа и для каждого — есть ли его цель в наборе; ' +
      'строка на вхождение, так что цель, названная дважды, — две строки. Раздел появляется т' +
      'олько когда включения в документе есть. Клик по строке переносит каретку к тому <code>' +
      '#include</code>, который эту цель называет.</p>',
    '<p>Метка имеет <b>три</b> значения, и третье важно: <code>набора нет</code> — это не «' +
      'фрагмент пропал», а «искать пока негде». Набор — это папка рядом с документом, а у нес' +
      'охранённого документа папки нет, поэтому до первого сохранения все цели помечены так. ' +
      '<code>НЕТ</code> появляется только когда папка есть и в ней действительно нет такого ф' +
      'айла.</p>',
    '<h3 id="note.case-mismatch"><code>note.case-mismatch</code> — цель есть, но в другом р' +
      'егистре</h3>',
    '<pre><a href="ex:14">#include "intro"</a>             →  (пусто)</pre>',
    '<p>При этом в наборе лежит <code>Intro.spintax</code> — и движок всё равно выдаёт «так' +
      'ой цели нет», а Studio добавляет свою заметку про регистр. Регистр важен: <code>intro<' +
      '/code> и <code>Intro</code> — разные цели. Windows открыл бы файл в любом регистре, по' +
      'этому Studio ищет по набору, а не по файловой системе: иначе предпросмотр расходился б' +
      'ы с боевым сервером на том же документе.</p>',
    '<h3 id="note.cycle"><code>note.cycle</code> — вставка по кругу</h3>',
    '<p>Если <code>loop.spintax</code> содержит <code>#include "loop"</code>, то:</p>',
    '<pre><a href="ex:15">#include "loop"</a>              →  (пусто)</pre>',
    '<p>Движок подставляет пустоту вместо бесконечности. Заметка нужна, чтобы вы поняли, по' +
      'чему абзац исчез.</p>',
    '<hr>',
    '<h2 id="plurals">Множественное число</h2>',
    '<h3 id="plural.arity"><code>plural.arity</code> — форм не столько, сколько требует лок' +
      'аль</h3>',
    '<pre><a href="ex:16">#set %n% = 5</a>' +
      #10 +
      '<a href="ex:16">%n% {plural %n%: товар|товара}</a>   →  5 ｛plural 5: товар|товара｝</pr' +
      'e>',
    '<p><b>Не пустота — движок печатает конструкцию целиком</b>, заменив обычные скобки на ' +
      'широкие <code>｛｝</code>. Так он говорит: «я это увидел и не смог применить». Незаметны' +
      'м это не назовёшь, и это хорошо: молча пропавший абзац искали бы дольше.</p>',
    '<p>Русскому нужно три формы, английскому две — <code>{plural %n%: file|files}</code>. ' +
      'Локаль берётся из селектора над правой панелью, а не из языка интерфейса.</p>',
    '<p><b>Пустота бывает по другой причине, и её легко спутать.</b> Движок проверяет в так' +
      'ом порядке:</p>',
    '<pre><a href="ex:17">{plural %n%: {товар|штука}|товара}</a>   →  ｛plural %n%: ｛товар|ш' +
      'тука｝|товара｝   скобки внутри форм' +
      #10 +
      '<a href="ex:18">{plural %n%: товар|товара}</a>           →  (пусто)   счётчик не число' +
      ': %n% не определён</pre>',
    '<p>Первое — <code>plural.nested-brackets</code>. Второе панель тоже пометит как <code>' +
      'plural.arity</code>, но <b>пустота в выводе не от неё</b>: счётчик проверяется раньше ' +
      'числа форм, <code>%n%</code> здесь не определён, и рендер останавливается, не дойдя до' +
      ' подсчёта. Поэтому пример без <code>#set %n%</code> показал бы пустоту при любом числе' +
      ' форм — и о самой арности не сказал бы ничего.</p>',
    '<p>Панель и вывод здесь говорят о разном, и это не противоречие: строку в панели стави' +
      'т <b>проверка</b>, которая считает формы в тексте и до счётчика ей дела нет; пустоту д' +
      'аёт <b>рендер</b>, у которого свой порядок. Определите счётчик числом — как в примере ' +
      'выше — и увидите, что делает арность на самом деле.</p>',
    '<h3 id="plural.count-macro"><code>plural.count-macro</code> — счётчик берёт значение и' +
      'з <code>#set</code></h3>',
    '<pre><a href="ex:19">#set %n% = {1|2}</a>' +
      #10 +
      '<a href="ex:19">%n% {plural %n%: товар|товара|товаров}</a>' +
      #10 +
      '                             →  1</pre>',
    '<p>Смотрите, что осталось в выводе: <b>число напечаталось, а существительного нет</b>.' +
      ' Значение <code>#set</code> разворачивается заново при каждой ссылке, поэтому в слот с' +
      'чётчика попадает не результат <code>1</code> или <code>2</code>, а сам текст <code>{1|' +
      '2}</code> — а он не число, и вся конструкция даёт пустоту. Разойтись счётчик с формой ' +
      'не могут: движок скорее уберёт слово целиком.</p>',
    '<p><code>#def</code> ведёт себя иначе — он разворачивает значение один раз за рендер, ' +
      'поэтому в слот счётчика попадает уже число:</p>',
    '<pre><a href="ex:20">#def %n% = {1|2}</a>' +
      #10 +
      '<a href="ex:20">%n% {plural %n%: товар|товара|товаров}</a>' +
      #10 +
      '                             →  1 товар</pre>',
    '<p>Строки в панели при этом нет вообще. Отсюда и правило: счётчиком делайте обычное чи' +
      'сло или <code>#def</code>, но не <code>#set</code>.</p>',
    '<h3 id="plural.nested-brackets"><code>plural.nested-brackets</code> — скобки внутри фо' +
      'рм</h3>',
    '<pre><a href="ex:21">{plural %n%: {товар|штука}|товара|товаров}</a>   →  ｛plural %n%: ' +
      '｛товар|штука｝|товара|товаров｝</pre>',
    '<p>Обратите внимание на вывод: движок печатает конструкцию <b>широкими</b> скобками <c' +
      'ode>｛ ｝</code> вместо обычных. Так он показывает, что разобрать не смог, не ломая при ' +
      'этом разметку вокруг.</p>',
    '<hr>',
    '<h2 id="permutations">Перестановки</h2>',
    '<h3 id="permutation.unknown-key"><code>permutation.unknown-key</code> — неизвестный кл' +
      'юч в настройке</h3>',
    '<pre><a href="ex:22">[&lt;foo=1&gt;а|б|в]</a>               →  Бfoo=1вfoo=1а</pre>',
    '<p>Смотрите внимательно на вывод: неизвестный ключ не игнорируется — он попадает в тек' +
      'ст как <b>разделитель</b> между элементами. Ключи: <code>minsize</code>, <code>maxsize' +
      '</code>, <code>sep</code>, <code>lastsep</code>.</p>',
    '<h3 id="permutation.minsize-not-integer"><code>permutation.minsize-not-integer</code> ' +
      '— минимум задан не числом</h3>',
    '<pre><a href="ex:23">[&lt;minsize=два&gt;а|б|в]</a>         →  Б в а</pre>',
    '<p>Нечисловое значение отбрасывается вместе со своим ограничением, и берётся значение ' +
      'по умолчанию — то есть все элементы.</p>',
    '<h3 id="permutation.maxsize-not-integer"><code>permutation.maxsize-not-integer</code> ' +
      '— максимум задан не числом</h3>',
    '<pre><a href="ex:24">[&lt;maxsize=много&gt;а|б|в]</a>       →  Б в а</pre>',
    '<p>Ровно то же самое с другого конца: ограничение сверху пропадает, и в выводе снова в' +
      'се элементы.</p>',
    '<hr>',
    '<h2 id="notes">Заметки Studio, которым нечего показать</h2>',
    '<p>Три заметки ниже нельзя продемонстрировать примером в этом документе — и причина в ' +
      'каждом случае своя, названная. Статьи у них всё равно есть: справка обязана отвечать н' +
      'а <b>любой</b> код, который может показать панель, иначе строка в панели ведёт в никуд' +
      'а.</p>',
    '<h3 id="note.raw-sentinel"><code>note.raw-sentinel</code> — служебный символ в тексте<' +
      '/h3>',
    '<p>Символы U+E000–U+E005 движок использует для внутренней разметки и <b>удаляет</b> пе' +
      'ред разбором. Если они попали в шаблон (обычно копипастом из другого редактора), Studi' +
      'o об этом говорит: предпросмотр и боевой сервер их не покажут.</p>',
    '<p>Примера здесь нет намеренно: эти символы невидимы, и строка с ними в документе выгл' +
      'ядела бы пустой — показать было бы нечего.</p>',
    '<h3 id="note.unknown-target"><code>note.unknown-target</code> — набор пуст, и судить н' +
      'е о чем</h3>',
    '<p>Появляется, когда набор рядом с документом <b>пуст</b>: ни одного шаблона, кроме эт' +
      'ого. Проверить цель не по чему, поэтому Studio не говорит «цели нет» — она говорит, чт' +
      'о не может ответить. Стоит появиться в папке хотя бы одному шаблону, и заметка уступае' +
      'т место обычной диагностике <code>include.unknown-target</code>, которая уже отвечает ' +
      'по существу.</p>',
    '<p>У несохранённого документа набора нет <b>совсем</b>, и это третий случай, не этот: ' +
      'вставки тогда остаются в выводе дословно, а панель о них молчит. Сохраните документ — ' +
      'и вставки заработают.</p>',
    '<p>Примера здесь нет по построению: у примеров этого документа набор объявлен выше и н' +
      'е пуст.</p>',
    '<h3 id="note.too-deep"><code>note.too-deep</code> — вставки вложены слишком глубоко</h' +
      '3>',
    '<p>Движок останавливается на двадцатом уровне вложенных <code>#include</code> и дальше' +
      ' подставляет пустоту. Ограничение семейное: так же поступают движки для JS, PHP и Pyth' +
      'on, поэтому документ, упёршийся в него, ведёт себя одинаково везде.</p>',
    '<p>Примера нет из-за размера: чтобы его показать, потребовался бы двадцать один файл.<' +
      '/p>',
    '<hr>',
    '<h2 id="abbreviations">Молчание, которое встречают все: сокращения</h2>',
    '<h3 id="abbreviations-0">Сокращение оставляет следующее слово строчным</h3>',
    '<pre><a href="ex:25">цена 100 руб. наша скидка ждёт</a>   →  Цена 100 руб. наша скидка' +
      ' ждёт' +
      #10 +
      '<a href="ex:26">цена 100 ххх. наша скидка ждёт</a>   →  Цена 100 ххх. Наша скидка ждёт' +
      '</pre>',
    '<p>Две строки, отличающиеся одним словом, и второе слово каждой показывает правило: по' +
      'сле <code>руб.</code> предложение остаётся строчным, после <code>ххх.</code> — начинае' +
      'тся с прописной. Движок ставит прописную после точки — но не после сокращения, которое' +
      ' он знает, и не после конструкций вида <code>и.о.</code> или <code>т.д.</code>. Диагно' +
      'стики нет никакой: заметить можно только по выводу.</p>',
    '<p><b>Список на 46 записей, и 29 из них русские:</b></p>',
    '<table border=1 cellpadding=4 cellspacing=0 width="100%">',
    '<tr><th></th><th></th></tr>',
    '<tr><td>русские</td><td><code>соц эл см ср ст ул пр пер г р руб коп тыс млн млрд трлн ' +
      'доп напр прим изд обл респ стр табл рис мин макс тел факс</code></td></tr>',
    '<tr><td>английские</td><td><code>etc vs mr mrs ms dr prof sr jr inc ltd co corp no st ' +
      'ave blvd</code></td></tr>',
    '</table>',
    '<p>Обе половины работают в <b>любой</b> локали — правило вообще не спрашивает, какой я' +
      'зык вы выбрали.</p>',
    '<p>Кусается это чаще, чем кажется, потому что <code>г.</code>, <code>ул.</code>, <code' +
      '>стр.</code>, <code>см.</code> — обычные слова русской прозы:</p>',
    '<pre><a href="ex:27">дом 5 г. москва</a>                  →  Дом 5 г. москва' +
      #10 +
      '<a href="ex:28">смотрите стр. 12. там всё есть</a>   →  Смотрите стр. 12. Там всё есть' +
      '</pre>',
    '<p>В первой строке <code>москва</code> осталась строчной — сокращение <code>г.</code> ' +
      'заэкранировало её, хотя это название города. Во второй видно, что правило потокенное: ' +
      '<code>стр.</code> экранирует, а <code>12.</code> — нет, и <code>Там</code> встало с пр' +
      'описной. Переписывайте фразу, а не боритесь с правилом: то же экранирование не даёт по' +
      'ставить прописную после <code>т.е.</code> в середине предложения, а это случай куда бо' +
      'лее частый.</p>',
    '<hr>',
    '<h2 id="correct">Как выглядит правильное</h2>',
    '<p>Для контраста — то же самое, разобранное без единого замечания:</p>',
    '<pre><a href="ex:29">цена {дешёвая|дорогая}</a>       →  Цена дешёвая</pre>',
    '<pre><a href="ex:30">[&lt;minsize=2;sep=", "&gt;а|б|в]</a>  →  В, б</pre>',
    '<pre><a href="ex:31">#set %vip% = 1</a>' +
      #10 +
      '<a href="ex:31">{?vip?для вас|для всех}</a>      →  Для вас</pre>',
    '<pre><a href="ex:32">#set %n% = 5</a>' +
      #10 +
      '<a href="ex:32">%n% {plural %n%: товар|товара|товаров}</a>   →  5 товаров</pre>',
    '<pre><a href="ex:33">до /# заметка #/ после</a>       →  До после</pre>',
    '<hr>',
    '<h2 id="faq">Часто спрашивают</h2>',
    '<p><b>Почему моя переменная с русским именем не работает?</b> Имена переменных — тольк' +
      'о латиница. <code>%имя%</code> вообще не считается ссылкой на переменную: движок печат' +
      'ает его как текст и <b>не выдаёт никакой диагностики</b>. А <code>#set %имя% = Мир</co' +
      'de> — это уже <code>set.malformed</code>. Значения при этом любые: <code>#set %city% =' +
      ' Москва</code> совершенно нормально.</p>',
    '<p><b>Почему одна и та же ошибка показана дважды?</b> Круговые ссылки выдаются на кажд' +
      'ое участвующее определение — это два разных места, которые нужно посмотреть.</p>',
    '<p><b>Почему в панели «ошибка», а вывод выглядит правильно?</b> Так бывает при повторн' +
      'ом определении: рендер корректен (побеждает последнее значение), но документ неоднозна' +
      'чен. Вердикт про документ, а не про конкретный вывод.</p>',
    '<p><b>Я переключил локаль — и в документе появилась ошибка. Что я сломал?</b> Ничего. ' +
      'Число форм множественного числа — свойство ЯЗЫКА: английскому нужно две (<code>page|pa' +
      'ges</code>), русскому три (<code>товар|товара|товаров</code>). Текст, написанный под о' +
      'дин язык, при переключении локали становится неверным для другого, и движок честно об ' +
      'этом говорит. Так ведёт себя и демо-документ, с которым открывается Studio: он английс' +
      'кий, и на локали <code>ru</code> его <code>{plural %pages%: page|pages}</code> — уже о' +
      'шибка.</p>',
    '<p><b>Почему абзац просто исчез?</b> Две частые причины, и обе выше: неизвестная цель ' +
      '<code>#include</code> и вставка по кругу. Обе выводят пустоту. Третья, на которую дума' +
      'ют чаще всего, — неверное число форм у множественного числа — <b>не</b> пустота: движо' +
      'к печатает конструкцию целиком в широких скобках <code>｛｝</code>. Пустоту там даёт неч' +
      'исловой счётчик, а не число форм.</p>'
  );

  { The conditions the outputs were measured under, and the template set. }
  HELP_LOCALE: array[0..1] of string = ('en', 'ru');
  HELP_SEED: array[0..1] of LongWord = (7, 7);
  HELP_INC_FIRST: array[0..1] of Integer = (0, 3);
  HELP_INC_LAST: array[0..1] of Integer = (2, 5);
  HELP_INC_NAME: array[0..5] of string = (
    'frag',
    'loop',
    'Intro',
    'frag',
    'loop',
    'Intro'
  );
  HELP_INC_TEXT: array[0..5] of string = (
    'Fragment',
    '#include "loop"',
    'Introduction',
    'фрагмент',
    '#include "loop"',
    'вступление'
  );

  { The templates the `ex:N` links point at, verbatim as the fixture ran them. }
  HELP_EX_FIRST: array[0..1] of Integer = (0, 33);
  HELP_EX_LAST: array[0..1] of Integer = (32, 66);
  HELP_EX_TEMPLATE: array[0..66] of string = (
    'a price {cheap|dear',
    'a price {cheap|dear]',
    'a price cheap} and all',
    '#set city = Boston' +
      #10 +
      'in %city%',
    '#def pages = {1|3}' +
      #10 +
      '%pages%',
    '#set %x% = first' +
      #10 +
      '#set %x% = second' +
      #10 +
      '%x%',
    '#def %x% = #include "frag"' +
      #10 +
      '%x%',
    'hello, %name%',
    '#set %brand% = {Vulkan}' +
      #10 +
      'casino %brand%',
    '#set %x% = a %x% b' +
      #10 +
      '%x%',
    '#set %x% = %y%' +
      #10 +
      '#set %y% = %x%' +
      #10 +
      '%x%',
    'before #include "frag" after',
    '#include "frag"',
    '#include "nosuch"',
    '#include "intro"',
    '#include "loop"',
    '#set %n% = 5' +
      #10 +
      '%n% {plural %n%: item|items|itemses}',
    '{plural %n%: item|items}',
    '{plural %n%: item|items|itemses}',
    '#set %n% = {1|2}' +
      #10 +
      '%n% {plural %n%: item|items}',
    '#def %n% = {1|2}' +
      #10 +
      '%n% {plural %n%: item|items}',
    '{plural %n%: {item|thing}|items}',
    '[<foo=1>a|b|c]',
    '[<minsize=two>a|b|c]',
    '[<maxsize=many>a|b|c]',
    'Ltd. our prices are low',
    'Xyz. our prices are low',
    'a price {cheap|dear}',
    '[<minsize=2;sep=", ">a|b|c]',
    '#set %vip% = 1' +
      #10 +
      '{?vip?for you|for everyone}',
    '#set %n% = 5' +
      #10 +
      '%n% {plural %n%: item|items}',
    'before /# a note #/ after',
    'hello %café% and %name%',
    'цена {дешёвая|дорогая',
    'цена {дешёвая|дорогая]',
    'цена дешёвая} и всё',
    '#set city = Москва' +
      #10 +
      'в %city%',
    '#def pages = {1|3}' +
      #10 +
      '%pages%',
    '#set %x% = первый' +
      #10 +
      '#set %x% = второй' +
      #10 +
      '%x%',
    '#def %x% = #include "frag"' +
      #10 +
      '%x%',
    'привет, %name%',
    '#set %brand% = {Vulkan}' +
      #10 +
      'казино %brand%',
    '#set %x% = а %x% б' +
      #10 +
      '%x%',
    '#set %x% = %y%' +
      #10 +
      '#set %y% = %x%' +
      #10 +
      '%x%',
    'до #include "frag" после',
    '#include "frag"',
    '#include "нетакого"',
    '#include "intro"',
    '#include "loop"',
    '#set %n% = 5' +
      #10 +
      '%n% {plural %n%: товар|товара}',
    '{plural %n%: {товар|штука}|товара}',
    '{plural %n%: товар|товара}',
    '#set %n% = {1|2}' +
      #10 +
      '%n% {plural %n%: товар|товара|товаров}',
    '#def %n% = {1|2}' +
      #10 +
      '%n% {plural %n%: товар|товара|товаров}',
    '{plural %n%: {товар|штука}|товара|товаров}',
    '[<foo=1>а|б|в]',
    '[<minsize=два>а|б|в]',
    '[<maxsize=много>а|б|в]',
    'цена 100 руб. наша скидка ждёт',
    'цена 100 ххх. наша скидка ждёт',
    'дом 5 г. москва',
    'смотрите стр. 12. там всё есть',
    'цена {дешёвая|дорогая}',
    '[<minsize=2;sep=", ">а|б|в]',
    '#set %vip% = 1' +
      #10 +
      '{?vip?для вас|для всех}',
    '#set %n% = 5' +
      #10 +
      '%n% {plural %n%: товар|товара|товаров}',
    'до /# заметка #/ после'
  );

  { The `###` articles: page, id, title, and whether the id is a diagnostic code. }
  HELP_ANCHOR_FIRST: array[0..1] of Integer = (0, 24);
  HELP_ANCHOR_LAST: array[0..1] of Integer = (23, 47);
  HELP_ANCHOR_PAGE: array[0..47] of Integer = (
    2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9
  );
  HELP_ANCHOR_ID: array[0..47] of string = (
    'bracket.unclosed',
    'bracket.mismatched',
    'bracket.unexpected-closing',
    'set.malformed',
    'def.malformed',
    'definition.duplicate-name',
    'def.include-in-value',
    'variable.undefined',
    'variable.self-reference',
    'variable.circular-reference',
    'includes-0',
    'include.unknown-target',
    'note.case-mismatch',
    'note.cycle',
    'plural.arity',
    'plural.count-macro',
    'plural.nested-brackets',
    'permutation.unknown-key',
    'permutation.minsize-not-integer',
    'permutation.maxsize-not-integer',
    'note.raw-sentinel',
    'note.unknown-target',
    'note.too-deep',
    'abbreviations-0',
    'bracket.unclosed',
    'bracket.mismatched',
    'bracket.unexpected-closing',
    'set.malformed',
    'def.malformed',
    'definition.duplicate-name',
    'def.include-in-value',
    'variable.undefined',
    'variable.self-reference',
    'variable.circular-reference',
    'includes-0',
    'include.unknown-target',
    'note.case-mismatch',
    'note.cycle',
    'plural.arity',
    'plural.count-macro',
    'plural.nested-brackets',
    'permutation.unknown-key',
    'permutation.minsize-not-integer',
    'permutation.maxsize-not-integer',
    'note.raw-sentinel',
    'note.unknown-target',
    'note.too-deep',
    'abbreviations-0'
  );
  HELP_ANCHOR_TITLE: array[0..47] of string = (
    '`bracket.unclosed` — a bracket is opened and never closed',
    '`bracket.mismatched` — closed by a bracket of another kind',
    '`bracket.unexpected-closing` — a closing bracket with nothing open',
    '`set.malformed` — this `#set` line does not follow the rule',
    '`def.malformed` — this `#def` line does not follow the rule',
    '`definition.duplicate-name` — this name is already defined above',
    '`def.include-in-value` — `#include` inside a definition value',
    '`variable.undefined` — this variable is defined nowhere',
    '`variable.self-reference` — the definition refers to itself',
    '`variable.circular-reference` — the definitions refer in a circle',
    '`#include` only works from the start of a line',
    '`include.unknown-target` — no such target in the set',
    '`note.case-mismatch` — the target exists, in another case',
    '`note.cycle` — an include in a circle',
    '`plural.arity` — not as many forms as the locale asks for',
    '`plural.count-macro` — the count comes from `#set`, and that rerolls on every referenc' +
      'e',
    '`plural.nested-brackets` — brackets inside the plural forms',
    '`permutation.unknown-key` — unknown key in the permutation config',
    '`permutation.minsize-not-integer` — minsize is not a whole number',
    '`permutation.maxsize-not-integer` — maxsize is not a whole number',
    '`note.raw-sentinel` — a control character in the text',
    '`note.unknown-target` — the set is empty, so there is nothing to judge by',
    '`note.too-deep` — includes nested too deeply',
    'An abbreviation keeps the next word lowercase',
    '`bracket.unclosed` — скобка открыта и не закрыта',
    '`bracket.mismatched` — скобка закрыта скобкой другого вида',
    '`bracket.unexpected-closing` — закрывающая скобка без открывающей',
    '`set.malformed` — строка `#set` написана не по правилу',
    '`def.malformed` — строка `#def` написана не по правилу',
    '`definition.duplicate-name` — это имя уже определено выше',
    '`def.include-in-value` — `#include` внутри значения определения',
    '`variable.undefined` — переменная нигде не определена',
    '`variable.self-reference` — определение ссылается само на себя',
    '`variable.circular-reference` — определения ссылаются по кругу',
    '`#include` работает только с начала строки',
    '`include.unknown-target` — такой цели нет в наборе',
    '`note.case-mismatch` — цель есть, но в другом регистре',
    '`note.cycle` — вставка по кругу',
    '`plural.arity` — форм не столько, сколько требует локаль',
    '`plural.count-macro` — счётчик берёт значение из `#set`',
    '`plural.nested-brackets` — скобки внутри форм',
    '`permutation.unknown-key` — неизвестный ключ в настройке',
    '`permutation.minsize-not-integer` — минимум задан не числом',
    '`permutation.maxsize-not-integer` — максимум задан не числом',
    '`note.raw-sentinel` — служебный символ в тексте',
    '`note.unknown-target` — набор пуст, и судить не о чем',
    '`note.too-deep` — вставки вложены слишком глубоко',
    'Сокращение оставляет следующее слово строчным'
  );
  HELP_ANCHOR_CODE: array[0..47] of Boolean = (
    True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, False
  );

function SpxHelpLangCode(ALang: Integer): string;
begin
  if (ALang < 0) or (ALang > High(HELP_LANG)) then Exit('');
  Result := HELP_LANG[ALang];
end;

function SpxHelpLangIndex(const ACode: string): Integer;
var i: Integer;
begin
  for i := Low(HELP_LANG) to High(HELP_LANG) do
    if HELP_LANG[i] = ACode then Exit(i);
  Result := -1;
end;

function SpxHelpSourcePath(ALang: Integer): string;
begin
  if (ALang < 0) or (ALang > High(HELP_PATH)) then Exit('');
  Result := HELP_PATH[ALang];
end;

function SpxHelpSourceDigest(ALang: Integer): string;
begin
  if (ALang < 0) or (ALang > High(HELP_DIGEST)) then Exit('');
  Result := HELP_DIGEST[ALang];
end;

function SpxHelpPageSlug(APage: Integer): string;
begin
  if (APage < 0) or (APage > High(HELP_SLUG)) then Exit('');
  Result := HELP_SLUG[APage];
end;

function SpxHelpPageIndex(const ASlug: string): Integer;
var i: Integer;
begin
  for i := Low(HELP_SLUG) to High(HELP_SLUG) do
    if HELP_SLUG[i] = ASlug then Exit(i);
  Result := -1;
end;

{ The one place the two-dimensional index is computed. -1 when either is out of range,
  so every caller above can answer with an empty string rather than a range error. }
function PageAt(ALang, APage: Integer): Integer;
begin
  if (ALang < 0) or (ALang >= SPX_HELP_LANG_COUNT) or
     (APage < 0) or (APage >= SPX_HELP_PAGE_COUNT) then Exit(-1);
  Result := ALang * SPX_HELP_PAGE_COUNT + APage;
end;

function SpxHelpPageTitle(ALang, APage: Integer): string;
var i: Integer;
begin
  i := PageAt(ALang, APage);
  if i < 0 then Exit('');
  Result := HELP_TITLE[i];
end;

function SpxHelpPageHtml(ALang, APage: Integer): string;
var i, n: Integer;
begin
  Result := '';
  i := PageAt(ALang, APage);
  if i < 0 then Exit;
  for n := HELP_FIRST[i] to HELP_LAST[i] do
  begin
    if n > HELP_FIRST[i] then Result := Result + #10;
    Result := Result + HELP_LINE[n];
  end;
end;

function SpxHelpAnchorCount(ALang: Integer): Integer;
begin
  if (ALang < 0) or (ALang >= SPX_HELP_LANG_COUNT) then Exit(0);
  Result := HELP_ANCHOR_LAST[ALang] - HELP_ANCHOR_FIRST[ALang] + 1;
end;

{ -1 rather than a range error, for the same reason PageAt gives. }
function AnchorAt(ALang, AIndex: Integer): Integer;
begin
  if (AIndex < 0) or (AIndex >= SpxHelpAnchorCount(ALang)) then Exit(-1);
  Result := HELP_ANCHOR_FIRST[ALang] + AIndex;
end;

function SpxHelpAnchorPage(ALang, AIndex: Integer): Integer;
var i: Integer;
begin
  i := AnchorAt(ALang, AIndex);
  if i < 0 then Exit(-1);
  Result := HELP_ANCHOR_PAGE[i];
end;

function SpxHelpAnchorId(ALang, AIndex: Integer): string;
var i: Integer;
begin
  i := AnchorAt(ALang, AIndex);
  if i < 0 then Exit('');
  Result := HELP_ANCHOR_ID[i];
end;

function SpxHelpAnchorTitle(ALang, AIndex: Integer): string;
var i: Integer;
begin
  i := AnchorAt(ALang, AIndex);
  if i < 0 then Exit('');
  Result := HELP_ANCHOR_TITLE[i];
end;

function SpxHelpAnchorIsCode(ALang, AIndex: Integer): Boolean;
var i: Integer;
begin
  i := AnchorAt(ALang, AIndex);
  Result := (i >= 0) and HELP_ANCHOR_CODE[i];
end;

function SpxHelpLocale(ALang: Integer): string;
begin
  if (ALang < 0) or (ALang > High(HELP_LOCALE)) then Exit('');
  Result := HELP_LOCALE[ALang];
end;

function SpxHelpSeed(ALang: Integer): LongWord;
begin
  if (ALang < 0) or (ALang > High(HELP_SEED)) then Exit(1);
  Result := HELP_SEED[ALang];
end;

function SpxHelpIncludeCount(ALang: Integer): Integer;
begin
  if (ALang < 0) or (ALang >= SPX_HELP_LANG_COUNT) then Exit(0);
  Result := HELP_INC_LAST[ALang] - HELP_INC_FIRST[ALang] + 1;
end;

function IncAt(ALang, AIndex: Integer): Integer;
begin
  if (AIndex < 0) or (AIndex >= SpxHelpIncludeCount(ALang)) then Exit(-1);
  Result := HELP_INC_FIRST[ALang] + AIndex;
end;

function SpxHelpIncludeName(ALang, AIndex: Integer): string;
var i: Integer;
begin
  i := IncAt(ALang, AIndex);
  if i < 0 then Exit('');
  Result := HELP_INC_NAME[i];
end;

function SpxHelpIncludeText(ALang, AIndex: Integer): string;
var i: Integer;
begin
  i := IncAt(ALang, AIndex);
  if i < 0 then Exit('');
  Result := HELP_INC_TEXT[i];
end;

function SpxHelpExampleCount(ALang: Integer): Integer;
begin
  if (ALang < 0) or (ALang >= SPX_HELP_LANG_COUNT) then Exit(0);
  Result := HELP_EX_LAST[ALang] - HELP_EX_FIRST[ALang] + 1;
end;

function SpxHelpExample(ALang, AIndex: Integer; out ATemplate: string): Boolean;
begin
  ATemplate := '';
  Result := (AIndex >= 0) and (AIndex < SpxHelpExampleCount(ALang));
  if Result then ATemplate := HELP_EX_TEMPLATE[HELP_EX_FIRST[ALang] + AIndex];
end;

function SpxHelpExampleOf(const AHref: string): Integer;
var i, n: Integer; digits: string;
begin
  Result := -1;
  if Copy(AHref, 1, 3) <> 'ex:' then Exit;
  digits := Copy(AHref, 4, MaxInt);
  if (digits = '') or (Length(digits) > 6) then Exit;
  { Added up here rather than through StrToIntDef, so this unit needs no uses clause
    at all -- it is a table of constants and nothing else, and it stays that way. }
  n := 0;
  for i := 1 to Length(digits) do
  begin
    if (digits[i] < '0') or (digits[i] > '9') then Exit;
    n := n * 10 + (Ord(digits[i]) - Ord('0'));
  end;
  Result := n;
end;

end.
