(*
 * SpxToolRail -- the narrow strip of tools, on the side the user chose.
 *
 * DeepL's column sits beside the OUTPUT because its tools change the output. Ours change the
 * TEMPLATE -- variables, and the group editor -- so its home is the left, next to the editor.
 * The side is a setting, which is the user's call and costs nothing as long as the layout asks
 * this class rather than hardcoding an alignment.
 *
 * IT SHOWS WHICH TOOL IS ON. A tool given a group lights up while its panel is showing, and
 * clicking the lit one puts it out -- which is how the bottom block is collapsed and given
 * back to the editor. That is the whole reason the rail carries state at all: the tab strip
 * used to say which panel was current, and once the rail says it the strip is 28 px of
 * duplication.
 *
 * IT IS ACCESS, NOT WORKSPACE. The panels behind these buttons hold tables -- diagnostics,
 * variables, the variant list -- and a table in a narrow column is unreadable, so the rail
 * raises the panel where the data fits instead of trying to be that place. The exception is a
 * tool that is narrow BY NATURE (a group's variants are a list, one per line); the group editor
 * lives in the rail's own slide-out, which is why the width is a constant here rather than a
 * number sprinkled through the form.
 *
 * ITS FOOT CARRIES THE BRAND, and that is a link rather than a tool. The mark is the ribbon
 * from spintax.net -- the site's LOGO, which is a different picture from the hexagon the
 * application wears as its icon -- and clicking it opens the site. It is deliberately NOT in
 * the tool array: the window addresses tools by index, and a brand added among them would
 * renumber every one of them. The rail does not know the URL either; it takes a handler, the
 * way every tool does.
 *
 * THE FACES ARE ICONS, FROM ONE SPRITE. A strip of four glyphs per size, sliced into an image
 * list -- LCL's TImageList.AddSliced is the sprite sheet by another name. The bytes are in
 * SpxIcons, generated by scripts/make-icons.py; the size is CHOSEN from the strips there rather
 * than scaled, because an image list draws at its own size and a stretched glyph is visible at
 * any scaling. That choice has to be REMADE when the scaling changes -- see DoAutoAdjustLayout,
 * which is the whole reason this class overrides anything. The letters D/V/Vr/G that stood here until the icons arrived also had to be
 * translated -- an icon does not, so the only thing a language changes now is the tooltip.
 *)
unit SpxToolRail;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Controls, Buttons, ExtCtrls, Graphics, ImgList,
  SpxUi, SpxIcons, SpxBrandMark, SpxTheme;

type
  { Which edge of the WINDOW the rail lives on. Not "which side of the editor": a user who
    moves it right expects it at the edge, the way every editor's side bar behaves. }
  TSpxRailSide = (spxRailLeft, spxRailRight);

  TSpxToolRail = class(TPanel)
  private
    FSide: TSpxRailSide;
    FIcons: TImageList;
    { What the sprite was last recoloured to, so the cache notices a theme change and not only
      a change of scaling. clNone means "as baked". }
    FIconInk: TColor;
    FButtons: array of TSpeedButton;
    FBrand: TSpeedButton;
    FBrandImgs: TImageList;
    { The height Place last laid the foot out for -- see Resize. }
    FPlacedFor: Integer;
    procedure SetSide(AValue: TSpxRailSide);
    procedure BuildIcons;
    procedure BuildBrand;
    procedure Place;
  protected
    { The mark sits a fixed distance off the BOTTOM edge, so it moves whenever the rail's
      height does -- and ONLY then. LCL calls Resize on every visible control in the form at
      the end of every autosize pass (control.inc:3103-3125), not just on the one that moved,
      and SetBounds re-arms the pass; laying out unconditionally therefore cost the whole form
      a second layout on every ripple. Acting only when the ROOM changed is the same guard the
      window's own clamp carries, and for the same reason (AGENTS.md: a clamp called from
      Resize fights every drag). }
    procedure Resize; override;
  public
    constructor Create(AOwner: TComponent); override;
    { The window's chrome colours. Off high contrast this assigns the same literal the
      constructor did, so it changes nothing; under one it hands the strip back to the system,
      which is the point -- a #F4F4F4 bar on a contrast theme's black desktop is a white slab. }
    procedure ApplyChrome(const AChrome: TSpxChrome);
    { One tool. AIcon is an index into the sprite (SPX_ICON_* in SpxIcons); AHint is the tool's
      name, which is the only part of a button a translation now touches.

      AGroup 0 is a plain button. Any other value makes it a LATCH: tools sharing a group are
      mutually exclusive, and because AllowAllUp is set, clicking the lit one puts it out --
      LCL flips Down on mouse-up and only then calls OnClick, so the handler reads Down to
      learn which of the two happened (speedbutton.inc:1025-1036, 148-177). }
    function AddTool(AIcon: Integer; const AHint: string; AOnClick: TNotifyEvent;
      AGroup: Integer = 0): TSpeedButton;
    { The brand at the rail's foot: the mark, and what to do when it is clicked. Called once,
      after the tools -- it is not one of them and does not take an index among them. }
    procedure SetBrand(const AHint: string; AOnClick: TNotifyEvent);
    { The lit state of the tool at AIndex, for a window that changed the panel some other way
      -- a menu item, or the group editor closing itself. }
    procedure SetDown(AIndex: Integer; AValue: Boolean);
    function IsDown(AIndex: Integer): Boolean;
    { The name of the tool at AIndex, for a language switch. }
    procedure SetTool(AIndex: Integer; const AHint: string);
    { Pick the strip that fits this display and lay the buttons out for it. Called by the
      window after a change of scaling -- and only after, because a form assigns its new
      PixelsPerInch AFTER its children have been adjusted (customdesigncontrol.inc:34-37):
      doing this from the child's own DoAutoAdjustLayout hook left every size one step
      behind, 36px faces on a 150% display and 54 at 200%. Measured, not reasoned. }
    procedure Rescale;
    { Take the outer slot on the chosen edge. Two controls aligned to the same edge are laid
      out in the order the parent holds them, and creating the rail first is NOT enough --
      measured: at startup it landed between the editor and the preview, and only a change of
      side put it right. Called once the panes exist, and again whenever the side changes. }
    procedure Reassert;
    property Side: TSpxRailSide read FSide write SetSide;
  end;

const
  { Wide enough for a 36px square face plus the four pixels either side that keep it off the
    editor's text. Everything else in this unit is derived from it. }
  SPX_RAIL_W = 44;

implementation

constructor TSpxToolRail.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  BevelOuter := bvNone;
  { A shade off the window, so the strip reads as chrome rather than as content. Not a
    border: a line here would be one more frame in a layout whose whole point is not having
    them. }
  Color := $00F4F4F4;
  FSide := spxRailLeft;
  Align := alLeft;
  Width := Px(Self, SPX_RAIL_W);
end;

procedure TSpxToolRail.ApplyChrome(const AChrome: TSpxChrome);
begin
  Color := AChrome.RailBack;
  { The glyphs go with the background: they are this control's only content, and BuildIcons
    now keys its cache on the ink as well as the size. }
  BuildIcons;
end;

{ The sprite, sliced. Built on the first tool rather than in the constructor because the size
  depends on the window's scaling, and a panel has no parent form while it is constructing
  itself (SpxUi.Px says the same thing at more length). }
procedure TSpxToolRail.BuildIcons;
var size_, len, i: Integer; p: Pointer; ink: TColor;
begin
  { 24 inside a 36 face at 100%: six pixels of air either side, which is the proportion every
    side bar uses. A glyph filling its button reads as a button that is too small. }
  size_ := SpxIconPickSize(Px(Self, 24));
  (* AND THE INK. These buttons have no caption -- AddTool sets an image and a hint and
     nothing else -- so the sprite IS the control, and the sprite is baked at rgb(60,60,60).
     The moment the rail takes the system's background under a contrast theme, its own tools
     measure 1.48:1: 316 pixels of #3C3C3C on #202020, counted off a photograph.

     Recorded because the first version of this slice missed it and said the opposite. The
     rail was "measured at 16.29:1" -- but that number was 27 pixels of white window frame in
     the sampled band, not the 316 pixels of glyph. The instrument found the brightest thing
     in the region rather than the thing the region is FOR. *)
  if SpxHighContrast then ink := ColorToRGB(clWindowText) else ink := clNone;
  if (FIcons <> nil) and (FIcons.Width = size_) and (FIconInk = ink) then Exit;
  FIconInk := ink;
  p := SpxIconStrip(size_, len);
  { The same list object, refilled -- the buttons hold a reference to it and would go blank
    if it were freed (SpxUi.SpxImagesFrom says why at more length). }
  FIcons := SpxImagesFrom(Self, FIcons, p, len, size_, size_, SPX_ICON_COUNT, ink);
  for i := 0 to High(FButtons) do
    if FButtons[i] <> nil then FButtons[i].Images := FIcons;
end;

{ The mark, at the width that fits the rail's face. One image rather than a strip: there is one
  of it, and an image list is still the only way LCL draws a glyph with its alpha intact on a
  speed button -- Glyph is a TBitmap and would lose it. }
procedure TSpxToolRail.BuildBrand;
var w, h, len: Integer; p: Pointer;
begin
  if FBrand = nil then Exit;
  { THE FACE'S FULL WIDTH, where a tool's glyph takes 24 of 36 -- and that is not the rule
    being broken but the same rule applied to a different shape. The air a tool gets on either
    side, the ribbon has above and below: 16 px of picture in a 36 px face. Asking for 24 here
    would leave an 11 px smudge. }
  w := SpxMarkPickWidth(Px(Self, 36));
  h := SpxMarkHeight(w);
  { A width the unit has no frame for is not a width to build from -- and the check is here
    rather than folded into the up-to-date test below, where it would have skipped the rebuild
    and left the PREVIOUS list in place at the wrong size. }
  if h = 0 then Exit;
  if (FBrandImgs <> nil) and (FBrandImgs.Width = w) then Exit;
  p := SpxMarkPng(w, len);
  if p = nil then Exit;
  FBrandImgs := SpxImagesFrom(Self, FBrandImgs, p, len, w, h, 1);
  FBrand.Images := FBrandImgs;
  FBrand.ImageIndex := 0;
end;

procedure TSpxToolRail.SetBrand(const AHint: string; AOnClick: TNotifyEvent);
begin
  if FBrand <> nil then Exit;
  FBrand := TSpeedButton.Create(Self);
  FBrand.Parent := Self;
  { HIDDEN UNTIL PLACE HAS PUT IT SOMEWHERE. A speed button is born 23x22 at 0,0
    (speedbutton.inc:46-47), so a mark whose frame could not be built would sit blank on top of
    the first tool and still open the site when clicked. Place shows it once it has bounds. }
  FBrand.Visible := False;
  FBrand.Flat := True;
  { A hand, because it is a link and nothing else in this strip is one. }
  FBrand.Cursor := crHandPoint;
  FBrand.Hint := AHint;
  FBrand.ShowHint := True;
  FBrand.OnClick := AOnClick;
  BuildBrand;
  Place;
end;

procedure TSpxToolRail.Resize;
begin
  inherited Resize;
  if ClientHeight = FPlacedFor then Exit;
  Place;
end;

procedure TSpxToolRail.Rescale;
begin
  { LCL has already scaled the buttons by proportion; this picks the strip that fits them now
    and puts them back on the grid Place owns, so one function decides the geometry at every
    scaling rather than two that have to agree. }
  Width := Px(Self, SPX_RAIL_W);
  BuildIcons;
  BuildBrand;
  Place;
end;

function TSpxToolRail.AddTool(AIcon: Integer; const AHint: string;
  AOnClick: TNotifyEvent; AGroup: Integer): TSpeedButton;
var n: Integer;
begin
  BuildIcons;
  n := Length(FButtons);
  SetLength(FButtons, n + 1);
  { A speed button rather than a TButton: it draws an image without a caption, and flat means
    the face is the icon until the pointer is over it -- the side-bar look, and the reason the
    rail can be a shade of the window rather than a row of raised boxes. }
  Result := TSpeedButton.Create(Self);
  Result.Parent := Self;
  Result.Flat := True;
  Result.Images := FIcons;
  Result.ImageIndex := AIcon;
  Result.Hint := AHint;
  Result.ShowHint := True;
  if AGroup <> 0 then
  begin
    Result.GroupIndex := AGroup;
    { Without this, SetDown refuses to put a lit button out (speedbutton.inc:165) and the
      block could never be collapsed by clicking the tool that opened it. }
    Result.AllowAllUp := True;
  end;
  Result.OnClick := AOnClick;
  FButtons[n] := Result;
  Place;
end;

procedure TSpxToolRail.SetTool(AIndex: Integer; const AHint: string);
begin
  if (AIndex < 0) or (AIndex > High(FButtons)) then Exit;
  FButtons[AIndex].Hint := AHint;
end;

procedure TSpxToolRail.SetDown(AIndex: Integer; AValue: Boolean);
begin
  if (AIndex < 0) or (AIndex > High(FButtons)) then Exit;
  FButtons[AIndex].Down := AValue;
end;

function TSpxToolRail.IsDown(AIndex: Integer): Boolean;
begin
  Result := (AIndex >= 0) and (AIndex <= High(FButtons)) and FButtons[AIndex].Down;
end;

procedure TSpxToolRail.Place;
var i, side_, y, w, h: Integer;
begin
  side_ := Px(Self, 36);
  y := Px(Self, 8);
  for i := 0 to High(FButtons) do
  begin
    FButtons[i].SetBounds(Px(Self, 4), y, side_, side_);
    Inc(y, side_ + Px(Self, 6));
  end;
  { And the brand at the foot, centred in the same column the faces occupy -- the ribbon is
    wider than it is tall, so it is the one thing here that is not a square on that grid. }
  if (FBrand <> nil) and (FBrandImgs <> nil) then
  begin
    w := FBrandImgs.Width;
    h := FBrandImgs.Height;
    FBrand.SetBounds(Px(Self, 4) + (side_ - w) div 2, ClientHeight - h - Px(Self, 12), w, h);
    { Below the last tool, or not at all: on a window too short to hold both, a mark drawn over
      a tool would be worse than a mark the reader has to make room for. Neither the mark's
      position nor the tools' depends on this, so it cannot oscillate. }
    FBrand.Visible := FBrand.Top > y;
  end;
  FPlacedFor := ClientHeight;
end;

procedure TSpxToolRail.Reassert;
begin
  { The parent's CHILD ORDER decides which of two controls aligned to the same edge gets the
    outer slot, and creating the rail first does not settle it: measured, the window opened
    with the rail between the editor and the preview, and re-assigning Align alone did not
    move it either -- the layout is recomputed when the form is shown, from this list. }
  if Parent <> nil then Parent.SetControlIndex(Self, 0);
  Align := alNone;
  if FSide = spxRailLeft then
  begin
    Left := 0;
    Align := alLeft;
  end
  else
  begin
    if Parent <> nil then Left := Parent.ClientWidth - Width;
    Align := alRight;
  end;
  { The width is the rail's own, not the alignment's: LCL keeps it across the change, but an
    explicit assignment is what makes that true rather than lucky. }
  Width := Px(Self, SPX_RAIL_W);
  Place;
end;

procedure TSpxToolRail.SetSide(AValue: TSpxRailSide);
begin
  if AValue = FSide then Exit;
  FSide := AValue;
  Reassert;
end;

end.
