(*
 * SpxToolRail -- the narrow strip of tools, on the side the user chose.
 *
 * DeepL's column sits beside the OUTPUT because its tools change the output. Ours change the
 * TEMPLATE -- variables, and the group editor -- so its home is the left, next to the editor.
 * The side is a setting, which is the user's call and costs nothing as long as the layout asks
 * this class rather than hardcoding an alignment.
 *
 * IT SHOWS WHICH TOOL IS ON. A tool given a group lights up while its panel is showing, and
 * clicking the lit one puts it out -- which is how the bottom block is collapsed and given
 * back to the editor. That is the whole reason the rail carries state at all: the tab strip
 * used to say which panel was current, and once the rail says it the strip is 28 px of
 * duplication.
 *
 * IT IS ACCESS, NOT WORKSPACE. The panels behind these buttons hold tables -- diagnostics,
 * variables, the variant list -- and a table in a narrow column is unreadable, so the rail
 * raises the panel where the data fits instead of trying to be that place. The exception is a
 * tool that is narrow BY NATURE (a group's variants are a list, one per line); the group editor
 * lives in the rail's own slide-out, which is why the width is a constant here rather than a
 * number sprinkled through the form.
 *
 * THE FACES ARE ICONS, FROM ONE SPRITE. A strip of four glyphs per size, sliced into an image
 * list -- LCL's TImageList.AddSliced is the sprite sheet by another name. The bytes are in
 * SpxIcons, generated by scripts/make-icons.py; the size is CHOSEN from the strips there rather
 * than scaled, because an image list draws at its own size and a stretched glyph is visible at
 * any scaling. That choice has to be REMADE when the scaling changes -- see DoAutoAdjustLayout,
 * which is the whole reason this class overrides anything. The letters D/V/Vr/G that stood here until the icons arrived also had to be
 * translated -- an icon does not, so the only thing a language changes now is the tooltip.
 *)
unit SpxToolRail;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Controls, Buttons, ExtCtrls, Graphics, ImgList, SpxUi, SpxIcons;

type
  { Which edge of the WINDOW the rail lives on. Not "which side of the editor": a user who
    moves it right expects it at the edge, the way every editor's side bar behaves. }
  TSpxRailSide = (spxRailLeft, spxRailRight);

  TSpxToolRail = class(TPanel)
  private
    FSide: TSpxRailSide;
    FIcons: TImageList;
    FButtons: array of TSpeedButton;
    procedure SetSide(AValue: TSpxRailSide);
    procedure BuildIcons;
    procedure Place;
  public
    constructor Create(AOwner: TComponent); override;
    { One tool. AIcon is an index into the sprite (SPX_ICON_* in SpxIcons); AHint is the tool's
      name, which is the only part of a button a translation now touches.

      AGroup 0 is a plain button. Any other value makes it a LATCH: tools sharing a group are
      mutually exclusive, and because AllowAllUp is set, clicking the lit one puts it out --
      LCL flips Down on mouse-up and only then calls OnClick, so the handler reads Down to
      learn which of the two happened (speedbutton.inc:1025-1036, 148-177). }
    function AddTool(AIcon: Integer; const AHint: string; AOnClick: TNotifyEvent;
      AGroup: Integer = 0): TSpeedButton;
    { The lit state of the tool at AIndex, for a window that changed the panel some other way
      -- a menu item, or the group editor closing itself. }
    procedure SetDown(AIndex: Integer; AValue: Boolean);
    function IsDown(AIndex: Integer): Boolean;
    { The name of the tool at AIndex, for a language switch. }
    procedure SetTool(AIndex: Integer; const AHint: string);
    { Pick the strip that fits this display and lay the buttons out for it. Called by the
      window after a change of scaling -- and only after, because a form assigns its new
      PixelsPerInch AFTER its children have been adjusted (customdesigncontrol.inc:34-37):
      doing this from the child's own DoAutoAdjustLayout hook left every size one step
      behind, 36px faces on a 150% display and 54 at 200%. Measured, not reasoned. }
    procedure Rescale;
    { Take the outer slot on the chosen edge. Two controls aligned to the same edge are laid
      out in the order the parent holds them, and creating the rail first is NOT enough --
      measured: at startup it landed between the editor and the preview, and only a change of
      side put it right. Called once the panes exist, and again whenever the side changes. }
    procedure Reassert;
    property Side: TSpxRailSide read FSide write SetSide;
  end;

const
  { Wide enough for a 36px square face plus the four pixels either side that keep it off the
    editor's text. Everything else in this unit is derived from it. }
  SPX_RAIL_W = 44;

implementation

constructor TSpxToolRail.Create(AOwner: TComponent);
begin
  inherited Create(AOwner);
  BevelOuter := bvNone;
  { A shade off the window, so the strip reads as chrome rather than as content. Not a
    border: a line here would be one more frame in a layout whose whole point is not having
    them. }
  Color := $00F4F4F4;
  FSide := spxRailLeft;
  Align := alLeft;
  Width := Px(Self, SPX_RAIL_W);
end;

{ The sprite, sliced. Built on the first tool rather than in the constructor because the size
  depends on the window's scaling, and a panel has no parent form while it is constructing
  itself (SpxUi.Px says the same thing at more length). }
procedure TSpxToolRail.BuildIcons;
var size_, len, i: Integer; p: Pointer;
begin
  { 24 inside a 36 face at 100%: six pixels of air either side, which is the proportion every
    side bar uses. A glyph filling its button reads as a button that is too small. }
  size_ := SpxIconPickSize(Px(Self, 24));
  if (FIcons <> nil) and (FIcons.Width = size_) then Exit;
  p := SpxIconStrip(size_, len);
  { The same list object, refilled -- the buttons hold a reference to it and would go blank
    if it were freed (SpxUi.SpxImagesFrom says why at more length). }
  FIcons := SpxImagesFrom(Self, FIcons, p, len, size_, size_, SPX_ICON_COUNT);
  for i := 0 to High(FButtons) do
    if FButtons[i] <> nil then FButtons[i].Images := FIcons;
end;

procedure TSpxToolRail.Rescale;
begin
  { LCL has already scaled the buttons by proportion; this picks the strip that fits them now
    and puts them back on the grid Place owns, so one function decides the geometry at every
    scaling rather than two that have to agree. }
  Width := Px(Self, SPX_RAIL_W);
  BuildIcons;
  Place;
end;

function TSpxToolRail.AddTool(AIcon: Integer; const AHint: string;
  AOnClick: TNotifyEvent; AGroup: Integer): TSpeedButton;
var n: Integer;
begin
  BuildIcons;
  n := Length(FButtons);
  SetLength(FButtons, n + 1);
  { A speed button rather than a TButton: it draws an image without a caption, and flat means
    the face is the icon until the pointer is over it -- the side-bar look, and the reason the
    rail can be a shade of the window rather than a row of raised boxes. }
  Result := TSpeedButton.Create(Self);
  Result.Parent := Self;
  Result.Flat := True;
  Result.Images := FIcons;
  Result.ImageIndex := AIcon;
  Result.Hint := AHint;
  Result.ShowHint := True;
  if AGroup <> 0 then
  begin
    Result.GroupIndex := AGroup;
    { Without this, SetDown refuses to put a lit button out (speedbutton.inc:165) and the
      block could never be collapsed by clicking the tool that opened it. }
    Result.AllowAllUp := True;
  end;
  Result.OnClick := AOnClick;
  FButtons[n] := Result;
  Place;
end;

procedure TSpxToolRail.SetTool(AIndex: Integer; const AHint: string);
begin
  if (AIndex < 0) or (AIndex > High(FButtons)) then Exit;
  FButtons[AIndex].Hint := AHint;
end;

procedure TSpxToolRail.SetDown(AIndex: Integer; AValue: Boolean);
begin
  if (AIndex < 0) or (AIndex > High(FButtons)) then Exit;
  FButtons[AIndex].Down := AValue;
end;

function TSpxToolRail.IsDown(AIndex: Integer): Boolean;
begin
  Result := (AIndex >= 0) and (AIndex <= High(FButtons)) and FButtons[AIndex].Down;
end;

procedure TSpxToolRail.Place;
var i, side_, y: Integer;
begin
  side_ := Px(Self, 36);
  y := Px(Self, 8);
  for i := 0 to High(FButtons) do
  begin
    FButtons[i].SetBounds(Px(Self, 4), y, side_, side_);
    Inc(y, side_ + Px(Self, 6));
  end;
end;

procedure TSpxToolRail.Reassert;
begin
  { The parent's CHILD ORDER decides which of two controls aligned to the same edge gets the
    outer slot, and creating the rail first does not settle it: measured, the window opened
    with the rail between the editor and the preview, and re-assigning Align alone did not
    move it either -- the layout is recomputed when the form is shown, from this list. }
  if Parent <> nil then Parent.SetControlIndex(Self, 0);
  Align := alNone;
  if FSide = spxRailLeft then
  begin
    Left := 0;
    Align := alLeft;
  end
  else
  begin
    if Parent <> nil then Left := Parent.ClientWidth - Width;
    Align := alRight;
  end;
  { The width is the rail's own, not the alignment's: LCL keeps it across the change, but an
    explicit assignment is what makes that true rather than lucky. }
  Width := Px(Self, SPX_RAIL_W);
  Place;
end;

procedure TSpxToolRail.SetSide(AValue: TSpxRailSide);
begin
  if AValue = FSide then Exit;
  FSide := AValue;
  Reassert;
end;

end.
