#!/usr/bin/env python3
"""Build the language menu's flag sprite and the Pascal unit that carries it.

A FLAG IS A COUNTRY, A MENU ITEM IS A LANGUAGE, and the two are not the same thing. Three of
the fourteen have no country that owns them: English is spoken by more people outside the UK
than in it, Spanish has nine times more speakers in the Americas than in Spain, Portuguese
twenty times more in Brazil than in Portugal. The flag is here because it makes a list of
fourteen scannable at a glance -- the ENDONYM beside it is what actually names the language,
and it is the endonym that is authoritative. The mapping below is one line per language on
purpose: changing GB to US, or PT to BR, is that one line and a re-run.

The pictures are Twemoji (CC-BY 4.0, Twitter/X) -- the credit belongs in the About box and the
NOTICE next to the icons'. They are VENDORED in assets/flags rather than fetched, unlike the
icon font: six kilobytes for all fourteen, so the build stays offline and a licence audit can
see exactly what ships.

Windows cannot do this itself: its emoji font deliberately renders a regional-indicator pair
as two letters rather than as a flag, so there is no way to draw these from a system font.

Usage:  python scripts/make-flags.py

Writes:  assets/flags/strip-<width>.png   -- the sprites, for looking at
         gui/SpxFlags.pas                 -- the same bytes, for shipping
"""
import io
import os

from PIL import Image

# ONE LINE PER LANGUAGE, in TSpxLang's order (src/SpxStudio.pas). The code is the language,
# the flag is the country picked for it, and the note is why when the two disagree.
FLAGS = [
    ('en', 'GB', 'the UK rather than the US: no reason beyond convention, and it is one edit'),
    ('ru', 'RU', ''),
    ('uk', 'UA', ''),
    ('be', 'BY', ''),
    ('sr', 'RS', ''),
    ('hr', 'HR', ''),
    ('bs', 'BA', ''),
    ('de', 'DE', 'also Austria and Switzerland'),
    ('fr', 'FR', 'also Belgium, Switzerland, Canada'),
    ('es', 'ES', 'most Spanish speakers are in the Americas'),
    ('it', 'IT', ''),
    ('pt', 'PT', 'Brazil has twenty times the speakers'),
    ('nl', 'NL', 'also Flanders'),
    ('tr', 'TR', ''),
]

# 16 is a Windows menu image at 100%; 20, 24 and 32 are the same at 125, 150 and 200%.
WIDTHS = sorted(set([16, 20, 24, 32]))   # sorted: the picker keeps the last that fits

# Every Twemoji flag is drawn in the same box inside its 72x72 square. Asserted rather than
# assumed: a source that changed shape would otherwise be cropped wrong and nobody would look.
BOX = (0, 10, 72, 62)

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def pascal_bytes(name, data):
    lines = ['  %s: array[0..%d] of Byte = (' % (name, len(data) - 1)]
    row = []
    for i, b in enumerate(data):
        row.append('$%02X' % b)
        if len(row) == 16:
            lines.append('    ' + ', '.join(row) + (',' if i < len(data) - 1 else ''))
            row = []
    if row:
        lines.append('    ' + ', '.join(row))
    lines.append('  );')
    return '\n'.join(lines)


def main():
    src_dir = os.path.join(HERE, 'assets', 'flags')
    sources = []
    for code, cc, _ in FLAGS:
        path = os.path.join(src_dir, '%s.png' % cc)
        if not os.path.exists(path):
            raise SystemExit('missing flag for %s: %s' % (code, path))
        im = Image.open(path).convert('RGBA')
        if im.size != (72, 72) or im.getbbox() != BOX:
            raise SystemExit('%s is %s with bbox %s, not the 72x72 %s every other one is -- '
                             'crop it by hand or fix BOX' % (path, im.size, im.getbbox(), BOX))
        sources.append(im.crop(BOX))

    blobs = []
    for w in WIDTHS:
        h = round(w * (BOX[3] - BOX[1]) / (BOX[2] - BOX[0]))
        strip = Image.new('RGBA', (w * len(FLAGS), h), (0, 0, 0, 0))
        for i, im in enumerate(sources):
            strip.paste(im.resize((w, h), Image.LANCZOS), (i * w, 0))
        path = os.path.join(src_dir, 'strip-%d.png' % w)
        strip.save(path)
        buf = io.BytesIO()
        strip.save(buf, format='PNG')
        blobs.append((w, h, buf.getvalue()))
        print('%-28s %d x %d' % (os.path.relpath(path, HERE), strip.width, strip.height))

    unit = ['(*',
            ' * SpxFlags -- the language menu\'s flags, as bytes.',
            ' *',
            ' * GENERATED by scripts/make-flags.py from the Twemoji artwork vendored in',
            ' * assets/flags (CC-BY 4.0). Do not edit: change the mapping in the script and run',
            ' * it again. The credit belongs in the About box and the NOTICE, not only here.',
            ' *',
            ' * THE INDEX IS Ord(TSpxLang). A flag is a country and a menu item is a language;',
            ' * the script says at more length which of the fourteen have no country of their',
            ' * own and why the endonym beside the flag is the part that is authoritative.',
            ' *',
            ' * The cells are WIDER THAN TALL -- a flag is not a square, and a square cell would',
            ' * either letterbox it or stretch it. An LCL image list takes an independent width',
            ' * and height, so it does not have to be one.',
            ' *)',
            'unit SpxFlags;',
            '',
            '{$mode objfpc}{$H+}',
            '',
            'interface',
            '',
            'const',
            '  { Flags in the strip, in TSpxLang order. The suite checks this against the enum. }',
            '  SPX_FLAG_COUNT = %d;' % len(FLAGS),
            '',
            '  { The widths there are strips for, ascending, and the height that goes with each. }',
            '  SPX_FLAG_WIDTHS: array[0..%d] of Integer = (%s);' %
            (len(WIDTHS) - 1, ', '.join(str(w) for w, _, _ in blobs)),
            '  SPX_FLAG_HEIGHTS: array[0..%d] of Integer = (%s);' %
            (len(WIDTHS) - 1, ', '.join(str(h) for _, h, _ in blobs)),
            '',
            '{ The strip to use when a cell AWanted px wide is wanted: the largest that still',
            '  FITS, for the reason SpxIcons gives at more length -- an image list draws at its',
            '  own size, so a bigger strip is clipped rather than shrunk. AHeight comes back',
            '  with it because the two are not the same number.',
            '',
            '  Below the smallest strip the smallest strip comes back, larger than asked: it',
            '  is that or nothing. Takes a cell under %d px, which no display asks for. }'
            % WIDTHS[0],
            'procedure SpxFlagPickSize(AWanted: Integer; out AWidth, AHeight: Integer);',
            '',
            '{ The PNG strip for a width SpxFlagPickSize returned -- byte for byte the file in',
            '  assets/flags. It is a pointer INTO the executable image: read it, do not free',
            '  it, and do not write through it. }',
            'function SpxFlagStrip(AWidth: Integer; out ALen: Integer): Pointer;',
            '',
            'implementation',
            '',
            'const']
    for w, h, data in blobs:
        unit.append('  { %d x %d cells, %d flags wide }' % (w, h, len(FLAGS)))
        unit.append(pascal_bytes('SPX_FLAGS_%d' % w, data))
        unit.append('')
    unit += ['procedure SpxFlagPickSize(AWanted: Integer; out AWidth, AHeight: Integer);',
             'var i: Integer;',
             'begin',
             '  AWidth := SPX_FLAG_WIDTHS[Low(SPX_FLAG_WIDTHS)];',
             '  AHeight := SPX_FLAG_HEIGHTS[Low(SPX_FLAG_HEIGHTS)];',
             '  for i := Low(SPX_FLAG_WIDTHS) to High(SPX_FLAG_WIDTHS) do',
             '    if SPX_FLAG_WIDTHS[i] <= AWanted then',
             '    begin',
             '      AWidth := SPX_FLAG_WIDTHS[i];',
             '      AHeight := SPX_FLAG_HEIGHTS[i];',
             '    end;',
             'end;',
             '',
             'function SpxFlagStrip(AWidth: Integer; out ALen: Integer): Pointer;',
             'begin',
             '  case AWidth of']
    for w, _, _ in blobs:
        unit.append('    %d: begin Result := @SPX_FLAGS_%d[0]; ALen := Length(SPX_FLAGS_%d); end;'
                    % (w, w, w))
    unit += ['  else',
             '    { Not one of ours: the menu size, so a caller that computed a width some',
             '      other way still gets flags rather than an empty strip. }',
             '    Result := @SPX_FLAGS_16[0];',
             '    ALen := Length(SPX_FLAGS_16);',
             '  end;',
             'end;',
             '',
             'end.',
             '']

    unit_path = os.path.join(HERE, 'gui', 'SpxFlags.pas')
    io.open(unit_path, 'w', encoding='utf-8', newline='').write('\n'.join(unit))
    print('%-28s %d bytes' % (os.path.relpath(unit_path, HERE), os.path.getsize(unit_path)))


if __name__ == '__main__':
    main()
