#!/usr/bin/env python3
"""Build the company mark the status bar's link wears, as PNG frames inside the executable.

THE COMPANY, NOT THE PRODUCT. spintax.net is the language and the engine family; 301ST is who
makes Studio. The rail already wears the first as a ribbon (`make-brandmark.py`), bottom left.
This is the second, bottom right, in the corner Windows keeps for the status bar -- two marks,
two corners, and neither of them pretending to be the other.

RASTERISED ONCE, VENDORED, AND NOT RE-RASTERISED HERE, for the reason `make-brandmark.py` gives
at length: nothing on the build machines turns an SVG into pixels, and CI has no Pillow either.
`assets/brand/301-512.png` is headless Chrome's render of the vendored `301.svg`, cropped to its
own ink -- 512x476, alpha intact. The vector is kept for provenance; the raster is what this
reads.

WHY HEIGHTS AND NOT WIDTHS, which is the one place this differs from the ribbon's generator. A
frame is named by the number its host CONSTRAINS. The ribbon hangs in the rail, whose face is a
width, so the ribbon's frames are widths. This one sits in a status bar, whose height is handed
down by the system font and cannot be argued with, so its frames are heights and the width
follows the aspect. Naming both by width would have made the caller compute the number it
actually has, which is how a glyph ends up one pixel proud of its bar.

The heights are what fits a status bar at 100/125/150/175/200% -- about 23 px at 100%, so 16
with air around it -- plus two below for a bar a smaller system font makes shorter. A frame is
RESIZED from the 512 with LANCZOS, never upscaled.

THE INK IS NOT THE SOURCE'S. The mark is drawn in the brand blue and shipped that way, but the
window recolours it to the system ink as it slices (`SpxImagesFrom`'s AInk), the same as the
tool glyphs -- a link in a status bar has to stay legible in a contrast theme, and 1.5:1 blue on
grey is not legible. The colour lives in the SVG so the vector stays the brand's; the pixels the
reader sees are the theme's.

Pure Pillow and stdlib, run by hand like the other generators here.

Usage:  python scripts/make-companymark.py

Writes: gui/SpxCompanyMark.pas
"""
import io
import os

from PIL import Image

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(HERE, 'assets', 'brand', '301-512.png')
OUT = os.path.join(HERE, 'gui', 'SpxCompanyMark.pas')

# A status bar's face at 100/125/150/175/200%, and two below it.
HEIGHTS = [12, 14, 16, 20, 24, 28, 32]


def fail(message):
    raise SystemExit('make-companymark: %s' % message)


def load():
    if not os.path.exists(SOURCE):
        fail('no %s -- the vendored render of the company mark is the input' % SOURCE)
    im = Image.open(SOURCE)
    if im.mode != 'RGBA':
        fail('the source is %s; the mark sits on a themed bar and needs its alpha' % im.mode)
    if im.getbbox() != (0, 0, im.width, im.height):
        fail('the source has empty margins -- it must be cropped to its own ink, so a frame '
             'is the mark and not the mark inside padding')
    if not (0.9 < im.width / float(im.height) < 1.3):
        fail('the source is %dx%d, aspect %.3f -- that is not the near-square mark this was '
             'written for' % (im.width, im.height, im.width / float(im.height)))
    return im


def frame(im, height):
    """One frame, at HEIGHT, keeping the source's aspect."""
    if height > im.height:
        fail('a %d px frame would upscale the %d px source' % (height, im.height))
    width = int(round(height * im.width / float(im.height)))
    if width < 1:
        fail('a %d px frame is under a pixel wide' % height)
    small = im.resize((width, height), Image.LANCZOS)
    buf = io.BytesIO()
    small.save(buf, format='PNG', optimize=True)
    data = buf.getvalue()
    # Read back what was written, the way the suite will: the PNG's own IHDR, not the numbers
    # that produced it.
    back = Image.open(io.BytesIO(data))
    if (back.width, back.height) != (width, height):
        fail('the %d px frame came back %dx%d' % (height, back.width, back.height))
    return width, data


def pas_bytes(name, data):
    out = ['  %s: array[0..%d] of Byte = (' % (name, len(data) - 1)]
    for i in range(0, len(data), 16):
        row = ', '.join('$%02X' % b for b in data[i:i + 16])
        out.append('    ' + row + (',' if i + 16 < len(data) else ''))
    out.append('  );')
    return out


def main():
    im = load()
    frames = [(h,) + frame(im, h) for h in HEIGHTS]

    u = ['(*',
         ' * SpxCompanyMark -- the 301ST mark the status bar links with, as bytes.',
         ' *',
         ' * GENERATED by scripts/make-companymark.py from assets/brand/301-512.png, which is a',
         ' * render of assets/brand/301.svg. Do not edit: change the source and run the script',
         ' * again.',
         ' *',
         ' * THE COMPANY, NOT THE PRODUCT. spintax.net is the language and the engine family and',
         ' * wears the ribbon on the rail; 301ST makes Studio and wears this, in the opposite',
         ' * corner. Two marks, two corners, neither pretending to be the other.',
         ' *',
         ' * A frame is named by its HEIGHT, because a status bar hands its height down from the',
         ' * system font and the width is what is left over -- the mirror of the ribbon, whose',
         " * host constrains a width. The bytes travel INSIDE the executable because R0 ships as",
         ' * one offline file (spec §11).',
         ' *',
         ' * The pixels are the brand blue; the window recolours them to the system ink as it',
         ' * slices, the same as the tool glyphs. A link in a status bar has to survive a',
         ' * contrast theme.',
         ' *)',
         'unit SpxCompanyMark;',
         '',
         '{$mode objfpc}{$H+}',
         '',
         'interface',
         '',
         'const',
         '  { The heights there are frames for, ascending. }',
         '  SPX_CO_HEIGHTS: array[0..%d] of Integer = (%s);'
         % (len(frames) - 1, ', '.join(str(f[0]) for f in frames)),
         '',
         '{ The tallest frame that fits AWanted, or the shortest when nothing does -- the same',
         '  rule SpxIconPickSize and SpxMarkPickWidth use, so every glyph in the window chooses',
         '  alike. }',
         'function SpxCompanyPickHeight(AWanted: Integer): Integer;',
         '',
         '{ The width that goes with a height this unit has a frame for, or 0 for one it does',
         "  not. Asked rather than computed: the aspect is the picture's, not a constant a",
         '  caller should carry. }',
         'function SpxCompanyWidth(AHeight: Integer): Integer;',
         '',
         '{ The PNG for a height, byte for byte. It is a pointer INTO the executable image: read',
         '  it, do not free it, and do not write through it. }',
         'function SpxCompanyPng(AHeight: Integer; out ALen: Integer): Pointer;',
         '',
         'implementation',
         '',
         'const']
    for i, (h, w, data) in enumerate(frames):
        u.append('  { %d x %d }' % (w, h))
        u += pas_bytes('SPX_CO_%d' % h, data)
        if i < len(frames) - 1:
            u.append('')
    u += ['',
          '  SPX_CO_WIDTHS: array[0..%d] of Integer = (%s);'
          % (len(frames) - 1, ', '.join(str(f[1]) for f in frames)),
          '',
          'function SpxCompanyPickHeight(AWanted: Integer): Integer;',
          'var i: Integer;',
          'begin',
          '  Result := SPX_CO_HEIGHTS[Low(SPX_CO_HEIGHTS)];',
          '  for i := Low(SPX_CO_HEIGHTS) to High(SPX_CO_HEIGHTS) do',
          '    if SPX_CO_HEIGHTS[i] <= AWanted then Result := SPX_CO_HEIGHTS[i];',
          'end;',
          '',
          'function SpxCompanyWidth(AHeight: Integer): Integer;',
          'var i: Integer;',
          'begin',
          '  Result := 0;',
          '  for i := Low(SPX_CO_HEIGHTS) to High(SPX_CO_HEIGHTS) do',
          '    if SPX_CO_HEIGHTS[i] = AHeight then Exit(SPX_CO_WIDTHS[i]);',
          'end;',
          '',
          'function SpxCompanyPng(AHeight: Integer; out ALen: Integer): Pointer;',
          'begin',
          '  ALen := 0;',
          '  Result := nil;',
          '  case AHeight of']
    for h, w, data in frames:
        u.append('    %d: begin Result := @SPX_CO_%d[0]; ALen := Length(SPX_CO_%d); end;'
                 % (h, h, h))
    u += ['  end;',
          'end;',
          '',
          'end.',
          '']

    io.open(OUT, 'w', encoding='utf-8', newline='').write('\n'.join(u))
    print('source %dx%d, aspect %.4f' % (im.width, im.height, im.width / float(im.height)))
    for h, w, data in frames:
        print('  %2d x %2d   %5d bytes' % (w, h, len(data)))
    print('%-30s %d bytes' % (os.path.relpath(OUT, HERE), os.path.getsize(OUT)))


if __name__ == '__main__':
    main()
